Extend button to also be of type "link" so that it can enable navigation
selsa-inube/design-system pull request #100
Opened 2023-04-14 17:47 UTC by Andresbl123

There are situations in which a <Button /> should be used to enable the navigation of the user to a different route of the app. This RFC asks the team to extend the <Button /> so that it can be used to allow navigation inside a router.

2023-04-17 16:32 UTC, cmarin001 commented
debido a las ultimas actualizaciones, debemos integrar con lo que lleva la rama main

2023-04-18 14:03 UTC, cmarin001 approved these changes
cumple con los requerimientos

2023-04-18 21:21 UTC, wfercanas requested changes

2023-04-18 21:21 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +  const shouldRenderLink = type === "link" && path;
Aquí se interpreta shouldRenderLink como si fuera una variable booleana (es decir, si debe o no debe renderizar un link). Sin embargo, el retorno de la expresión de la derecha es `path` si efectivamente `type === "link"`.

Creo que esta línea sobra, más bien:
1. Ya estamos validando que type sea uno de los type válidos. Así que esta parte ya está ok.
2. Aunque en propTypes no podemos poner path como isRequired, sí podemos evaluar si la persona fue consistente y al poner el button de type = "link" también pasó un path o no. Si no lo pasó, podemos hacer un `console.warn()`

2023-04-18 21:21 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +
Cambiemos esta composición. Hay varias cosas a considerar:
1. Ahora mismo el grueso de los estilos está amarrado a `StyledButton`. Podemos separar esos estilos de ahí usando `import { css } from 'styled-components'`. Así, podemos trasladar esos estilos a una variable javaScript aparte y luego por dentro del StyledButton usar esa variable.
2. El anterior cambio permite que podamos también usar esa misma variable dentro del `StyledLink`,

Con la solución anterior, podemos ajustar el componente <Button /> en index.js así:
```js
if (type === "link") {
  return (
    <StyledLink>
      // ..........
    </StyledLink>
  )
}

return (
  <StyledButton>
    // ....
  </StyledButton>
)

```

3. Con este cambio, estamos envolviendo todo el componente o por un Link o por un button al nivel del styled-component, no anidando react components. De hecho, hacer click en el botón, así sea en una esquinita, desencadena la navegación, no como creo que quedaría ahorita y es que sólo haciendo click en el texto es que se puede navegar.
4. Además, el return dentro del StyledLink puede ser un poco distinto. Sí podemos tener un Link disabled, pero un Link con loading no tiene mucho sentido. Así que por dentro la ternaria que evalúa el loading puede ser diferente.

2023-04-18 21:21 UTC, wfercanas commented on src/components/inputs/Button/stories/ButtonController.jsx
> +  return (
En la práctica el papá del Button no será el encargado de crear el router. El router es más un componente global de la aplicación.
Por lo tanto, este componente podríamos borrarlo y más bien puede agregar el BrowserRouter como decorador en las historias.

Nota: tampoco se justifica crear un estado para verificar el uso del handleClick, si es el caso, puede pasar la función como args() en las historias e imprimir algo en consola para ver que la función sí se ejecuta.

2023-04-20 00:40 UTC, Andresbl123 commented on src/components/inputs/Button/index.jsx
> +const LinkButton = ({ isDisabled, variant, appearance, children }) => (
Resuelto

2023-04-20 00:40 UTC, Andresbl123 commented on src/components/inputs/Button/index.jsx
> +  const shouldRenderLink = type === "link" && path;
Resuelto

2023-04-20 00:40 UTC, Andresbl123 commented on src/components/inputs/Button/stories/ButtonController.jsx
> +  return (
Resuelto

2023-04-20 00:40 UTC, Andresbl123 commented on src/components/inputs/Button/index.jsx
> +
Resuelto

2023-04-26 02:48 UTC, wfercanas requested changes

2023-04-26 02:48 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +    isfullwidth = false,
Se acepta que cuando estemos pasando props a los styled-components, hagamos un cambio sutil de nombre para que la consola no presente errores por atributos que no reconoce con mayúscula o que no son boolean, etc.., pero que el `<Button />` puertas para afuera sí mantenga las props con el estándar que venimos manejando, no las cambiemos (los cambios de nombre, si toca, los hacemos adentro).

Es importante para que usar la librería sea sencillo, si no en unos casos como iconBefore sí uso camelCase y en otros como isfullwidth no.

2023-04-27 22:59 UTC, wfercanas approved these changes

2023-04-27 22:59 UTC, merged