Create <BreadcrumbEllipsis/>
selsa-inube/design-system pull request #103
Opened 2023-04-18 16:17 UTC by cmarin001

2023-04-18 20:48 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-18 22:12 UTC, wfercanas requested changes

2023-04-18 22:12 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +    isActive = defaultIsActive,
El BreadcrumbEllipsis nunca puede ser active, eliminemos esta prop y sus complementos.

2023-04-18 22:12 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +    id,
Yo creo que podemos quitar esta prop, pues nadie va a implementar este componente solo, es más un componente utilitario que estará utilizando Breadcrumbs por debajo para resumir la lista de links.

Como no es un link en sí mismo, sino un paso previo a la selección de un link, no debería haber problema.

2023-04-18 22:12 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsisController.jsx
No hace falta crear un controller. La Ellipsis nunca es active y es apenas un utilitario para mostrar links verticales. Hacer click en él no actualiza el estado de nadie, sólo muestra opciones adicionales para navegar.

2023-04-18 22:12 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
El RFC solicita que este componente abra el menú. Por lo que adicional a los cambios solicitados aquí, hay que terminar primero el BreadcrumbMenu para poder continuar con este componente y agregar la posibilidad de abrir y cerrar el menú.

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +  id: PropTypes.string.isRequired,
esta propiedad ya no es necesaria, en este objeto

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.js
> +import { BreadcrumbEllipsisController } from "./BreadcrumbEllipsisController";
Según las recomendaciones, no hace falta implementar un controller ni sus complementos , "La Ellipsis nunca es active y es apenas un utilitario para mostrar links verticales".

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.js
> +  id: "privileges",
esta props no se implementa, quitar de esta parte y de Default.argTypes

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsisController.jsx
> +const BreadcrumbEllipsisController = (props) => {
no se debería usar un controlador para este archivo: "La Ellipsis nunca es active y es apenas un utilitario para mostrar links verticales."

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/stories/props.js
> +const id = {
Esta props no esta en uso, validar que no se importe en las historias o en otro archivos

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/stories/props.js
> +const isActive = {
Esta props no esta en uso, validar que no se importe en las historias o en otro archivos

2023-04-21 16:26 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
aun se encuentra el archivo controller

2023-04-21 21:35 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
Incidencia Resuelta

2023-04-21 21:35 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +  id: PropTypes.string.isRequired,
Incidencia Resuelta

2023-04-21 21:35 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.js
> +import { BreadcrumbEllipsisController } from "./BreadcrumbEllipsisController";
Incidencia Resuelta

2023-04-21 21:35 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.js
> +  id: "privileges",
Incidencia Resuelta

2023-04-21 21:36 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsisController.jsx
> +const BreadcrumbEllipsisController = (props) => {
Incidencia Resuelta

2023-04-21 21:36 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/stories/props.js
> +const id = {
Incidencia Resuelta

2023-04-21 21:36 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/stories/props.js
> +const isActive = {
Incidencia Resuelta

2023-04-24 23:19 UTC, Andresbl123 commented
cumple con los requerimientos

2023-04-25 02:34 UTC, wfercanas requested changes
Además de agregar la historia extra solicitada, validar con Leonardo a nivel de UX si se espera que si el usuario hace click en cualquier lugar por fuera del menú, el menú se cierre (actualmente queda abierto hasta hacer click nuevamente en la Ellipsis).

2023-04-25 02:34 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.js
Agreguemos una historia donde aparezca <Breadcrumbs /> completo y por dentro aparezca la Ellipsis para ser usada en la navegación.

2023-04-30 03:00 UTC, wfercanas requested changes

2023-05-02 19:58 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +    const handleClickOutside = (event) => {
resuelto

2023-05-02 19:59 UTC, cmarin001 commented on src/components/navigation/BreadcrumbMenu/styles.js
> +  position: fixed;
resuelto

2023-05-02 20:49 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  if (crumbs.length > maxCrumbs) {
resuelto

2023-05-02 20:51 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +      crumb: `${crumbs[0].charAt(0).toUpperCase() + crumbs[0].slice(1)}`,
resuelto

2023-05-02 21:04 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +      path: `/${crumbs[0]}`,
Resuelto

2023-05-02 21:24 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +      path: `/${crumbs.slice(-1)[0]}`,
resuelto

2023-05-02 22:55 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  const routesForEllipsis = crumbs.slice(1, -1).map((item) => ({
resuelto

2023-05-02 22:57 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +    const middleCrumb = {
Resuelto

2023-05-03 00:50 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +      <StyledContainerEllipsis ref={containerRef} onClick={handleEllipsisClick}>
resuelto

2023-05-05 21:03 UTC, wfercanas requested changes

2023-05-05 21:03 UTC, wfercanas commented on src/components/navigation/Breadcrumbs/index.jsx
> +    breadcrumbItems[0].path = "/";
Aquí corrige el path del crumb 0, pero para este punto los demás crumbs armaron sus paths de forma incorrecta.

2023-05-05 21:03 UTC, wfercanas commented on src/components/navigation/BreadcrumbMenu/styles.js
> +  position: absolute;
Aunque aquí ya se corrige el scroll, ahora el menú está apareciendo corrido hacia la izquierda, no aparece debajo de la elipsis (como se ve en el figma)

2023-05-05 22:22 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +    path: `/${crumbs.slice(0, index + 1).join("/")}`,
resuelto

2023-05-05 23:07 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +    return [firstCrumb, "", lastCrumb];
resuelto

2023-05-05 23:11 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +    breadcrumbItems[0].path = "/";
resuelto

2023-05-05 23:46 UTC, cmarin001 commented on src/components/navigation/BreadcrumbMenu/styles.js
> +  position: absolute;
resuelto

2023-05-08 14:40 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-11 20:18 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  crumbs.unshift("Home");
Esta inserción pienso que es muy a lo maldita sea, y genera mas complicaciones de lo que pueda llegar a aportar , cómo por ejemplo en la función `getBreadcrumbItems`, donde es muy confuso el porque el corte del array

2023-05-11 20:58 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
> +function getBreadcrumbItems(crumbs, maxCrumbs) {
Esta función es bastante compleja, por un lado cuando se utiliza la función y se le pasa  `crumbs`, el tiene que realizar el slice desde la posición 1, porque ya viene "Home" (por el unshift`), poor otro lado esta armando un objeto, objeto que también se arma en  `getRoutesForEllipsis()` y en donde dicha función también se debe hacer un  `slice` desde la posición por lo mencionado anteriormente, aquí podríamos incluir el la propiedad id, en el armado del objeto.

2023-05-11 21:00 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
> +        index === 0 || index === breadcrumbItems.length - 1 || index === 2
Esta parte es algo complicada, porque estamos tomando tres posiciones del array  cuando los `crumbs.length` es mayor de `maxCrumbs`,  entre las que se toma se toma el índice 2,  pero la surge la duda, de porque este, y no el 1 o el 3, no es claro, pero a la final tomamos esa posición para desecharla e insertar   `<BreadcrumbEllipsis />`, no es muy claro, por otro lado como se necesita insertar el `Home`  en los `crumbs`, podríamos preocuparnos de eso en esta parte, para tener los `crumbs`

2023-05-11 21:00 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  const maxCrumbs = isDesktop ? 5 : 3;
Para evitar estos valores quemados, podríamos crear una variables globales, en el sentido del scope del componente para manejarlos

2023-05-11 21:00 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
>    return (
Aquí se podría majar un return condicional es decir un return para cuando `crumbs.length > maxCrumbs` cosa que si no es así, no entre y muestre el `<BreadcrumbLink />`

2023-05-11 21:06 UTC, Andresbl123 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +    const handleClickOutside = (event) => {
La función aun se encuentra del useEffect

2023-05-11 21:52 UTC, cmarin001 commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +    const handleClickOutside = (event) => {
resuelto

2023-05-11 23:56 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
>    return (
resuelto

2023-05-11 23:57 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  crumbs.unshift("Home");
resuelto

2023-05-12 00:26 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  const routesForEllipsis = getRoutesForEllipsis(crumbs);
resuelto

2023-05-12 00:27 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +function getBreadcrumbItems(crumbs, maxCrumbs) {
resuelto

2023-05-12 01:20 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +        index === 0 || index === breadcrumbItems.length - 1 || index === 2
resuelto

2023-05-12 13:29 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +  const maxCrumbs = isDesktop ? 5 : 3;
resuelto

2023-05-15 15:40 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-15 20:02 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +      .filter((_, index) => index !== 0);
resuelto

2023-05-15 20:02 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +          key={breadcrumbItems[1].path}
resuelto

2023-05-16 14:56 UTC, Andresbl123 commented
cumple con los requerimientos

2023-05-16 20:32 UTC, wfercanas approved these changes

2023-05-16 20:32 UTC, merged