Develop the `<NavLink />` component
selsa-inube/design-system pull request #116
Opened 2023-04-26 00:13 UTC by Andresbl123

develop the link component to be used within the vertical menu on the left hand side of the applications.

2023-04-26 18:02 UTC, cmarin001 commented on src/components/navigation/MenuLink/index.jsx
> +    isdisabled = false,
mantengamos el standard que veniamos manejando de modo  que aqui seria isDisabled

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/stories/MenuLink.Controller.jsx
> +    <StyledList>
para que lo preparamos para una lista cuando al desplegarlo solo tenemos un unico elemento

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/stories/MenuLink.Default.stories.js
> +  isdisabled,
tener en cuenta lo del comentario anterior acerca de la convencion

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/stories/props.js
> +const isdisabled = {
tener en cuenta lo del comentario anterior acerca de la convencion

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/stories/MenuLink.Default.stories.js
> +  icons,
se va a pasar un unico icono por medio de esta variable, de modo que deberia de llamarse icon en singular y no icons en plurar

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/stories/props.js
> +const icons = {
se va a pasar un unico icono por medio de esta variable, de modo que deberia de llamarse icon en singular y no icons en plurar

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/styles.js
> +/* const getGrid = (icon, isSelected) => {
debemos asegurarnos de no dejar codigo comentado, de modo tal de que si este codigo no sirve a un proposito funcional deberiamos de quitarlo

2023-04-26 18:12 UTC, cmarin001 commented on src/components/navigation/MenuLink/styles.js
> +const StyledIcon = styled.div`
deberiamos hacer el uso del componente <Stack/> y asi evitar el uso de estas reglas "
  display: flex;
  justify-content: center;
  align-items: center;"

2023-04-27 03:50 UTC, Andresbl123 commented on src/components/navigation/MenuLink/index.jsx
> +    isdisabled = false,
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/stories/MenuLink.Controller.jsx
> +    <StyledList>
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/stories/MenuLink.Default.stories.js
> +  isdisabled,
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/stories/props.js
> +const isdisabled = {
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/stories/MenuLink.Default.stories.js
> +  icons,
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/stories/props.js
> +const icons = {
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/styles.js
> +/* const getGrid = (icon, isSelected) => {
Resuelto

2023-04-27 03:51 UTC, Andresbl123 commented on src/components/navigation/MenuLink/styles.js
> +const StyledIcon = styled.div`
Resuelto

2023-04-28 15:33 UTC, wfercanas requested changes
Aparte de los cambios solicitados, el componente se llama `<NavLink />`, no `<MenuLink />`. Hay que renombrar carpeta y archivos.

2023-04-28 15:33 UTC, wfercanas commented on src/components/navigation/MenuLink/index.jsx
> +      $icon={icon}
¿Por qué el uso de $ en el nombre de la variable?

2023-04-28 15:33 UTC, wfercanas commented on src/components/navigation/MenuLink/index.jsx
> +        </Stack>
Creo que no se justifica tener un Stack para un sólo elemento. 
1. Creo que este renderizado del icon se puede refactorizar.
2. El componente stack no recibe una prop que se llame isDisabled

2023-04-28 15:33 UTC, wfercanas commented on src/components/navigation/MenuLink/styles.js
El componente está apareciendo por default en fondo gris. Si evalúa los mockups de users/ puede ver que el menú en general va de fondo transparente para que se vea el fondo que traiga por default el Menu y luego sí empieza a ponerse gris con el hover o el select.

2023-04-28 20:26 UTC, Andresbl123 commented on src/components/navigation/MenuLink/index.jsx
> +      $icon={icon}
resuelto, perdón había mal interpretado esta parte: https://styled-components.com/docs/api#transient-props

2023-04-28 20:26 UTC, Andresbl123 commented on src/components/navigation/MenuLink/index.jsx
> +        </Stack>
Resuelto

2023-04-28 20:26 UTC, Andresbl123 commented on src/components/navigation/MenuLink/styles.js
Resuelto

2023-04-28 20:44 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-04-30 03:12 UTC, wfercanas requested changes

2023-04-30 03:12 UTC, wfercanas commented on src/components/navigation/NavLink/styles.js
> +const stilesIcons = css`
Se escribe styles. Quedaría mejor como `iconStyles`

2023-04-30 03:12 UTC, wfercanas commented on src/components/navigation/NavLink/styles.js
> +const StyledLink = styled(Link)`
El Link al llegar al DOM llega como un `<a>`, por lo que aplica un `cursor: pointer` sobre el texto cuando hay hover. Sería bueno extender ese comportamiento a todo el elemento, pues el cursor sólo cambia cuando está sobre el área que ocupa el Link

2023-05-02 14:25 UTC, Andresbl123 commented on src/components/navigation/NavLink/styles.js
> +const StyledLink = styled(Link)`
Resuelto

2023-05-04 03:53 UTC, wfercanas approved these changes

2023-05-04 03:53 UTC, merged