Develop the `<useMediaQueries />` hook
selsa-inube/design-system pull request #118
Opened 2023-04-26 17:57 UTC by cmarin001

2023-04-27 22:20 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-27 22:34 UTC, Andresbl123 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +      <p>Matches:</p>
Ya que estamos usando componentes de la librería, podríamos implementar el componente 'Text' para que se ajuste a la tipografía que estamos utilizando en la biblioteca.

2023-04-27 22:41 UTC, Andresbl123 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +            <Label htmlFor={query}>
Creo que aquí tambien podríamos usar el componente `<Text /> `

2023-04-27 23:43 UTC, cmarin001 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +      <p>Matches:</p>
resuelto

2023-04-27 23:43 UTC, cmarin001 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +            <Label htmlFor={query}>
resuelto

2023-04-28 13:56 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-28 17:02 UTC, wfercanas requested changes

2023-04-28 17:02 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  });
Las dos funciones anteriores, que sirven para hacer algunas validaciones, se pueden definir por fuera del custom hook. Cada una de esas funciones puede hacer return (no throw) de un error.

Luego, dentro del custom hook, puede usar un try... catch, para llamar esas validaciones y en caso de tener un catch, ahí sí hacer el throw.

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    if (queries.length > 0) {
Incidencia Resuelta

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +  const matches = useMediaQueries(queries);
Incidencia Resuelta

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +      updateState();
Incidencia Resuelta

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  }, [queries.join(",")]);
Incidencia Resuelta

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    if (typeof query !== "string" || query.trim() === "") {
Incidencia Resuelta

2023-04-28 20:09 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  });
Incidencia Resuelta

2023-04-28 21:28 UTC, Andresbl123 commented
cumple con los requerimientos

2023-04-30 00:40 UTC, wfercanas commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +  const matches = useMediaQueries(queries);
Le aplicó los cambios que pedía aquí a index.jsx, cuando en realidad eran sólo para este stories.js.

2023-05-03 01:13 UTC, cmarin001 commented on src/hooks/stories/ExampleMediaQueries.stories.js
> +  const matches = useMediaQueries(queries);
Incidencia Resuelta

2023-05-04 14:07 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-05 19:57 UTC, wfercanas requested changes

2023-05-05 19:57 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  const [matches, setMatches] = useState({});
En el primer return del hook está devolviendo un objeto vacío, eso puede causar que un componente que esté esperando una secuencia de true y false para los media queries que pasó al hook reciba un objeto que no le sirve y que rompa el layout.

2023-05-05 19:57 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    const validationError = validateQueries(queries);
Estamos haciendo la validación hasta después del primer renderizado, cuando pudimos haber hecho la validación desde un principio.

2023-05-05 19:57 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    setMatches(initializeState(mediaQueryList));
El estado se está inicializando muy tarde.

2023-05-05 19:57 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    return new Error("Invalid query: must not be an empty string");
Este return tiene implícito el if anterior. Sin embargo, si hay necesidad de extender el conjunto de validaciones por alguna razón, hay que empezar a concatenar if's en el find e if's luego para invalidQuery.

La propuesta de usar un try...catch es para que cada validación sea una función en sí misma, aislada y que retorna su propio error. De esa manera:
1. Extender el componente es sólo cuestión de agregar una nueva función que valide e insertarla en el try..catch. 
2. Si hay que modificar una validación, se modifica su función sin preocuparse de su relación con otras validaciones.

Nota: lo que sí logró mejorar aquí es que recorre el array una sola vez, en lugar de hacer un recorrido por cada función validadora. Entonces el try...catch habría que colocarlo más bien dentro de un forEach, que al estar recorriendo cada elemento, ejecute las funciones validadoras para ese elemento.

2023-05-05 19:57 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +      return new Error("Invalid query: must be a string");
Esta validación no está funcionando. Si para un número o un boolean en la primera posición del array de queries, no intercepta que hay un error:
![image](https://user-images.githubusercontent.com/36939686/236556903-f68e7430-a51e-498d-a173-d64db076a594.png)

2023-05-05 20:02 UTC, wfercanas requested changes

2023-05-05 20:02 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +        if (prevState[event.media] === event.matches) {
Este if es algo contradictorio. Se supone que el evento change se dispara cuando hay un cambio de true/false en un media query y si se dispara es porque cambió el valor que en ese momento está en el estado actual.
Por lo tanto, este if sería como dudar del evento change.

1. Si el evento change funciona correctamente, aplica el cambio al state de forma normal.
2. Si el evento se dispara aún cuando no haya cambio con respecto al estado actual (situación extraña), de todas formas el actuallizador del estado estaría sobreescribiendo los mismos datos que ya tiene prevState, así que a nivel de estado no hay ninguna inconsistencia y lo único que estaríamos haciendo es una optimización mínima para evitar ese sobreescribir.

Conclusión: la ganancia es mínima y parte del hecho de dudar del evento change, por lo que creo que no hace falta.

2023-05-05 20:04 UTC, wfercanas requested changes

2023-05-05 20:04 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +    const handleChange = (event) => {
No creo que haga falta crear un handleChange en cada ejecución del effect. La función puede definirse por fuera del callback del useEffect.

2023-05-08 17:14 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    const validationError = validateQueries(queries);
resuelto

2023-05-08 17:21 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    setMatches(initializeState(mediaQueryList));
resuelto

2023-05-08 17:33 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    const handleChange = (event) => {
resuelto

2023-05-08 17:40 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +        if (prevState[event.media] === event.matches) {
resuelto

2023-05-08 20:47 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    return new Error("Invalid query: must not be an empty string");
resuelto

2023-05-08 20:51 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +      return new Error("Invalid query: must be a string");
resuelto

2023-05-09 14:30 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-11 14:20 UTC, Andresbl123 commented on src/hooks/useMediaQueries.js
> +  const handleChange = (event, prevState) => {
aquí sería algo contraproducente. porque a la final tengo dos funciones para retornar un objeto `handleChange` y `changeHandler`, se podría validar para que reciba el estado anterior y retorne el nuevo, y esta podría ser la dunfión de escucha para los `Listener`.

2023-05-11 19:39 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +const validateArray = (arr, name) => {
resuelto

2023-05-11 19:49 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  validateArray(queries, "queries");
resuelto

2023-05-11 20:16 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    const handleChanges = mediaQueryList.map((mediaQueryObject) => {
resuelto

2023-05-11 20:28 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    initializeState(queries.map((query) => window.matchMedia(query)))
resuelto

2023-05-11 20:46 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  validateArray(queries, "queries");
resuelto

2023-05-11 20:47 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    const mediaQueryList = queries.map((query) => window.matchMedia(query));
resuelto

2023-05-11 21:04 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +      const changeHandler = (event) => {
resuelto

2023-05-11 21:28 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +      mediaQueryObject.addEventListener("change", changeHandler);
resuelto

2023-05-11 21:28 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +        mediaQueryList[index].removeEventListener("change", changeHandler);
resuelto

2023-05-11 21:33 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  useLayoutEffect(() => {
resuelto

2023-05-11 21:39 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  const handleChange = (event, prevState) => {
resuelto

2023-05-12 16:06 UTC, Andresbl123 commented on src/hooks/useMediaQueries.js
> +  validateArrayType(queries, "queries");
Creo que ejecutar estas funciones aquí de alguna forma hace compleja la función, en el sentido que le estamos asignando responsabilidades que se podrían manejar por separado dentro del `useMediaQueries`, esto haría que la función solo valide que los registros dentro del array no estén vacíos, y ya, e incluso en algún momento sería más fácil de testear, así como las demás funciones.

2023-05-12 16:06 UTC, Andresbl123 commented on src/hooks/useMediaQueries.js
> +    validateQueries(queries);
Con lo comentado a la función `validateQueries`, el bloque del try, iría solo hasta estas validaciones, y no incluiría a `useEffect`, ya que en ese punto, ya se han realizado las respectivas validaciones que se debe hacer a los datos.

2023-05-12 16:06 UTC, Andresbl123 commented on src/hooks/useMediaQueries.js
> +    const handleChange = useCallback((event, prevState) => {
No se si sea necesario utilizar el hook `useCallback`, en este custom hook, ya que a la final no hay renderizaciones, ya que no es un componente como tal, y pues la ganancia en el performance al utilizarlo, no lo ameritaría, y hace el código tenga un nivel de complejidad que la final no necesita.

2023-05-12 16:06 UTC, Andresbl123 commented on src/hooks/useMediaQueries.js
> +      const changeHandler = (event) => {
Esta función esta definida aún dentro del `useEffect`, la podemos sacar quitándole esta responsabilidad al hook

2023-05-12 20:54 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  validateArrayType(queries, "queries");
resuelto

2023-05-12 22:23 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    validateQueries(queries);
resuelto

2023-05-12 22:23 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +      const changeHandler = (event) => {
resuelto

2023-05-12 22:28 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +    const handleChange = useCallback((event, prevState) => {
resuelto

2023-05-15 14:04 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-15 19:15 UTC, wfercanas requested changes

2023-05-15 19:15 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  validateArrayNotEmpty(queries, "queries");
Es string "queries" no se recibe por props, por lo que nunca va a cambiar. Por lo tanto, cada validación dentro del error puede colocar directamente "queries" sin tener que recibir el texto como parámetro de la función.

2023-05-15 19:15 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  };
No es necesario tener tanto a `changeHandler` como a `handleChange`, con sólo `handleChange` es suficiente.

Esta función puede recibir directamente el evento y ya por dentro el setMatches tiene acceso a prevState.

2023-05-15 19:15 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  }, [mediaQueryList]);
Puede agregar `handleChange` al array de dependencias para cumplir con la regla de ESLint (exhaustive-deps).

2023-05-15 20:11 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  validateArrayNotEmpty(queries, "queries");
resuelto

2023-05-15 20:45 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  }, [mediaQueryList]);
resuelto

2023-05-15 20:49 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  };
resuelto

2023-05-16 20:20 UTC, wfercanas commented on src/hooks/useMediaQueries.js
> +  }, [mediaQueryList]);
Ahora que sacó la función del effect, ahora el error es que no debería estar en el array de dependencias 😅 . Quitemos la dependencia.

2023-05-16 20:29 UTC, cmarin001 commented on src/hooks/useMediaQueries.js
> +  }, [mediaQueryList]);
resuelto

2023-05-16 20:46 UTC, wfercanas approved these changes

2023-05-16 20:46 UTC, wfercanas approved these changes

2023-05-16 20:46 UTC, merged