Develop the `<Table />` component
selsa-inube/design-system pull request #129
Opened 2023-05-08 21:30 UTC by Andresbl123

In apps we will need a visual structure to render a bunch of data in a table. Analyse the custom component `<Table />` developed by the Linpar team, propose (if it is considered correct) a refactoring of this component and finally develop and publish a version of the component design system.

2023-05-24 20:23 UTC, cmarin001 commented on src/components/data/Table/interface.jsx
> +function TableUI(props) {
por favor revisar y corregir los errores que arroja storybook
![image](https://github.com/selsa-inube/design-system/assets/45011420/a9b34816-434c-4229-adb0-903e34952831)

2023-06-02 01:01 UTC, wfercanas requested changes

2023-06-02 01:02 UTC, wfercanas requested changes

2023-06-02 01:02 UTC, wfercanas commented on src/components/data/Table/stories/Default.stories.jsx
> +  entriesPagination: [
Esta propiedad no tiene sentido porque no es una prop del componente.

2023-06-02 21:54 UTC, Andresbl123 commented on src/components/data/Table/Pagination/styles.js
> +const StyledContentPagination = styled.div`
Resuelto

2023-06-02 21:54 UTC, Andresbl123 commented on src/components/data/Table/Pagination/styles.js
> +  flex-direction: row;
Resuelto

2023-06-02 21:54 UTC, Andresbl123 commented on src/components/data/Table/Pagination/styles.js
> +const StyledContentButtons = styled.div`
Resuelto

2023-06-02 21:54 UTC, Andresbl123 commented on src/components/data/Table/Pagination/styles.js
> +const StyledContentText = styled.div`
Resuelto

2023-06-02 21:54 UTC, Andresbl123 commented on src/components/data/Table/stories/Default.stories.jsx
> +  entriesPagination: [
resuelto

2023-06-06 21:24 UTC, cmarin001 commented
tenemos un error cuando se abre la historia `Pagination`
![image](https://github.com/selsa-inube/design-system/assets/45011420/e2ba9df5-a750-4fdf-813b-a8514c1ccc6a)

2023-06-07 18:45 UTC, wfercanas approved these changes

2023-06-07 19:22 UTC, merged