Develop the `<Nav />` component
selsa-inube/design-system pull request #131
Opened 2023-05-10 18:09 UTC by cmarin001

2023-05-12 14:20 UTC, Andresbl123 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +const Default = (args) => <Nav {...args} />;
El componente en la historia esta presentando una falla, ya que permite seleccionar dos opciones al tiempo cuando en `navObject` tiene la propiedad `subTitle` , y este comportamiento no se debería pasar, ya que es confuso porque es como estar en dos opciones del menu al mismo tiempo 
![image](https://github.com/selsa-inube/design-system/assets/74839801/29f5ccbe-7cf2-49cb-894d-384d717dbe91)

2023-05-12 15:01 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +const Nav = (props) => {
resuelto

2023-05-12 15:21 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +            <Stack key={index} direction="column" justifyContent="center">
resuelto

2023-05-12 15:21 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +const Default = (args) => <Nav {...args} />;
resuelto

2023-05-15 20:34 UTC, wfercanas requested changes

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +  decorators: [
Aparte de los decorators, puede agregar:
```js
parameters: {
  layout: "fullscreen"
}
```

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +          label: "Privilegios",
Dejar los ejemplos todos en inglés

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/interface.jsx
Si crea un archivo de interface es para dejar todo el jsx de la presentación del componente ahí y toda la lógica del componente en index.
Aquí sólo está pasando un pedazo, que es el map de routes, por lo que no se cumple el propósito de un archivo interface.

El componente Nav no amerita mucha lógica, por lo que creo que no necesita separar la lógica de lo presentacional con un interface.jsx, así que este fuente debería ir en index.jsx

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
Agregue una historia donde no haya subtítulos, como se ve en linpar.

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +        <SeparatorLine />
En el figma puede notar que entre los links y la línea de separación hay 16px. En el componente están pegados.

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/interface.jsx
> +      handleClick={() => handleClick(route.id)}
La tipografía de los NavLink está incorrecta. Debe ser un bodyMedium con font-size de 14px y aquí está de 16px.
Hay que arreglar el NavLink para que use lo tokens de tipografía correctos.

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +          <Text typo="labelMedium">© 2023 Sistemas Enlinea S.A</Text>
Cambiemos este texto por `©2023 - Inube`

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  };
Este mecanismo de selección de NavLink no nos funciona. El Nav debería ser capaz de identificar en qué ruta se encuentra la aplicación para así poder deducir cuál de todos los NavLink va activo.
Esto porque la navegación se hace no sólo haciendo click sobre el nav, sino que dentro cada pantalla puede haber redireccionamiento a otras partes de la aplicación.

Para más detalles, puede consultar cómo se resolvió ese problema en linpar.

2023-05-15 20:34 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +        {/* <div> */}
Eliminar div comentado.

2023-05-15 21:01 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +  decorators: [
resuelto

2023-05-15 21:53 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +          <Text typo="labelMedium">© 2023 Sistemas Enlinea S.A</Text>
resuelto

2023-05-15 21:53 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +        <SeparatorLine />
resuelto

2023-05-15 21:53 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
resuelto

2023-05-15 22:20 UTC, cmarin001 commented on src/components/navigation/Nav/interface.jsx
resuelto

2023-05-15 22:26 UTC, cmarin001 commented on src/components/navigation/Nav/interface.jsx
> +      handleClick={() => handleClick(route.id)}
resuelto

2023-05-15 22:54 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  };
resuelto

2023-05-15 22:57 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +        {/* <div> */}
resuelto

2023-05-17 17:34 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-18 17:04 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +          typoToken="titleMedium"
La prop se llama sólo `typo` y en los mockups está como "titleSmall"

2023-05-18 17:06 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +                  padding="0px 0px 26px 16px"
Este padding no está alineado con los mockups, allá tiene 16px en todas las direcciones.

2023-05-18 17:07 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +          margin="0px 0px 32px 0px"
Este margin + padding tampoco está alineado con los mockups.

2023-05-18 17:09 UTC, wfercanas commented on src/components/navigation/NavLink/styles.js
>    font-family: ${typography.ref.typeface.brand};
Revisemos que aqui estemos definiendo todas las propiedades tipográficas que expone `typography.sys.typescale.bodyMedium` y de paso que no estemos repitiendo la definición de la misma propiedad (como en este caso que tenemos 2 font-family)

2023-05-18 20:07 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +          typoToken="titleMedium"
resuelto

2023-05-19 00:11 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  const { title, navObject, logoutPath, handleClick } = props;
resuelto

2023-05-19 01:47 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +          margin="0px 0px 32px 0px"
resuelto

2023-05-19 01:47 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +                  padding="0px 0px 26px 16px"
resuelto

2023-05-19 03:36 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  const transformedGap = navObject.some((navSection) => navSection.subTitle)
resuelto

2023-05-19 03:46 UTC, cmarin001 commented on src/components/navigation/NavLink/styles.js
>    font-family: ${typography.ref.typeface.brand};
resuelto

2023-05-19 15:29 UTC, Andresbl123 commented
Ajustes realizados

2023-05-22 16:54 UTC, wfercanas requested changes

2023-05-22 16:54 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  Object.keys(navigation).forEach((key) => {
Esta función es muy necesaria si permitimos que el objeto navigation en su primer nivel de profundidad tenga secciones o links.

Sin embargo,creo que si permitimos esa flexibilidad, hacemos más complejo el componente y de pronto podamos organizar el tema un poco diferente.

Propongo que explore la opción de que, parecido a cómo hacen algunas API, hagamos lo siguiente:
1. En el primer nivel tengamos "title" y "sections" (en las API se suele llamar es "content"). 
2. Este sections contiene una o más sections.
3. Nunca dentro de sections van los links directamente. Siempre debe haber al menos un section.
4. Si solo viene un section, vamos directo al proceso de retorno sencillo. Si viene más de uno, pues hay que hacer el doble map del caso (map de sections y map de links)

Con lo anterior también aspiro a que no usemos recursividad.

2023-05-24 19:25 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  Object.keys(navigation).forEach((key) => {
resuelto

2023-05-25 21:14 UTC, Andresbl123 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +Default.args = {
Esta estructura de datos de la props discierne un poco de lo que se había planteado en revisiones anteriores, ya que dentro de `sections` no se manejaría un array sino objetos, se podría manejar la siguiente estructura para la props:

`
 {
  title: "MENU",

  sections: {
    administrate: {
      nameSections:"Administrate",    // por dentro van los NavLinks
      links:{
        privileges: {
          id: "privileges",
          label: "Privileges",
          icon: <MdKey />,
          path: "/privileges",
        },
      },
       
    },
    Requst:{
      nameSections:"Request",
      links:{
        ...
      },
    },
`

2023-05-26 20:44 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +Default.args = {
resuelto

2023-05-29 14:02 UTC, Andresbl123 commented on src/components/navigation/Nav/index.jsx
> +  const { title, sections, logoutPath, handleClick } = props;
el nombre de la props es `navigation` y dentro de este objeto tenemos la propiedad `title`  y ya no sería una props aparte

2023-05-29 15:23 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  const { title, sections, logoutPath, handleClick } = props;
resuelto

2023-05-29 15:27 UTC, cmarin001 commented on src/components/navigation/Nav/styles.js
> +  & p {
resuelto

2023-05-29 15:35 UTC, cmarin001 commented on src/components/navigation/Nav/stories/props.js
resuelto

2023-05-29 22:12 UTC, Andresbl123 commented
cumple con los requerimientos

2023-05-30 16:42 UTC, wfercanas requested changes

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  const getValues = (object) => Object.values(object);
Creo que esta función crea un nivel más de abstracción que no hace tanta falta. En la línea de abajo, intenta obtener las secciones, por lo que habría dos formas de hacerlo:
1. `const transformedSections = getValues(navigation.sections)`
2. `const transfromedSections = Object.values(navigation.sections)`

Ambas ocupan más o menos lo mismo, pero en el primer caso, necesito conocer qué hace la función getValues, su implementación. En el segundo caso estoy recurriendo a un método estándar de Object, por lo que ese sí es mucho más probable que lo lea y sepa lo que hace.

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  const transformedSections = getValues(navigation.sections);
En lugar de `transformedSections`, podemos llamarlo directamente `sections`

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  if (Object.keys(navigation.sections).length > 1) {
La extracción de keys y la evaluación del length podemos hacerla antes. Crear una variable que sea `totalSections` y con eso luego queda más fácil de usar.

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +  if (Object.keys(navigation.sections).length > 1) {
Podemos meter este if por dentro del return, de esa manera podemos evitar repetir el JSX del navigation.title, SeparatorLine, logout y footer.

Como ya creó un componente que recorre unos routes de una sección y devuelve los links, podemos crear otro componente que recorre los sections y devuelve el JSX para ese section.

Es decir, podríamos tener algo como:

```js
const Nav = () => {
  const sections = Object.keys(navigation.sections) // ['administrative', 'request']
  const firstSection = sections[0]

  return (
    <StyledNav>
      <Stack>
        //... {navigation.title}
        {totalSections > 1 
          ? <MultiSections navigation={navigation}> 
          : <OneSection navigation={navigation} firstSection={firstSection}/>
        }
      </Stack>
      <SeparatorLine />
      // ....
    </StyledNav>
  )
}

// Entonces aparte podemos hacer

const MultiSections = ({navigation}) => {
  const sections = Object.keys(navigation.sections) // ['administrative', 'request']

  return (
    <>
      {sections.map(section => (
        <Text>{navigation.sections[section].nameSections}</Text>
        <Links section={navigation.sections[section].links}/>
      ))}
    </>
  )
}

const OneSection = ({navigation, firstSection}) => {
  return (
    <>
      <Text>{navigation.sections[firstSection].nameSection}</Text>
      <Links section={navigation.sections[firstSection].links}/>
    </>  
  )
}


const Links = ({links}) => {
  // Aquí un map de los links que reciba y retornando los <NavLink />
}
```

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +        nameSections: "Administrate",
Cambiemos este nombre por sólo `name`

2023-05-30 16:42 UTC, wfercanas commented on src/components/navigation/Nav/stories/Nav.WithOutSubtitles.stories.jsx
> +  title: "navigation/Nav/WithOutSubtitles",
La historia sería `WithoutSections`

2023-05-30 19:48 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  const transformedSections = getValues(navigation.sections);
resuelto

2023-05-30 19:50 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  if (Object.keys(navigation.sections).length > 1) {
resuelto

2023-05-30 19:59 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  if (Object.keys(navigation.sections).length > 1) {
resuelto

2023-05-30 20:05 UTC, cmarin001 commented on src/components/navigation/Nav/stories/Nav.Default.stories.jsx
> +        nameSections: "Administrate",
resuelto

2023-05-30 20:08 UTC, cmarin001 commented on src/components/navigation/NavLink/index.jsx
> +      <StyledNavLink
para este caso en efecto si queda algo raro, sin embargo si lo dejamos del modo que se sugiere causaria un bug ya que solo toma el path para poder navegar y si uno clickea sobre el elemento ya sea en el icono o cerca al path no hace correctamente la navegacion esto se evidencia en web pero aun mas en mobile.

2023-05-30 20:41 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +  const getValues = (object) => Object.values(object);
resuelto

2023-05-30 22:49 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-31 23:23 UTC, wfercanas requested changes

2023-05-31 23:23 UTC, wfercanas commented on src/components/navigation/Nav/index.jsx
> +            }
Este Links creo que no debería ir dentro de llaves

2023-06-01 13:07 UTC, cmarin001 commented on src/components/navigation/Nav/index.jsx
> +            }
resuelto

2023-06-01 20:30 UTC, merged