Develop the `<FullscreenNav />` component
selsa-inube/design-system pull request #132
Opened 2023-05-15 13:43 UTC by Andresbl123

The `<FullscreenNav />` component is a fullscreen variant of the `<Nav />` component. It is decoupled from `<Nav />` for two reasons: the aesthetics may differ and the rendering depends on the use of React Portals. The component contains its own internal state to control when the menu is open. In addition, the component uses createPortal from 'react-dom' to render the menu inside a portal.

2023-05-16 22:04 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
>          <Stack direction="column" gap="24px">
a partir de aqui y hacia abajo debemos usar el componente <Nav/> si bien es cierto que aun no esta integrado como parte de main en el codigo base, considero que es prematuro hacerlo de este modo ya que tendriamos una duplicidad que no es necesaria ni optima

2023-05-16 22:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +import { MdMenu, MdClose, MdLogout } from "react-icons/md";
aqui no es necesaria la importacion de MdLogout

2023-05-16 22:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +        <Stack direction="column" gap="24px">
a partir de aqui y hacia abajo debemos usar el componente

si bien es cierto que aun no esta integrado como parte de main en el codigo base, considero que es prematuro hacerlo de este modo ya que tendriamos una duplicidad que no es necesaria ni optima

2023-05-16 22:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +          <Text typo="titleLarge" appearance="secondary">
este titulo hace parte del componente de nav por lo cual tampoco lo necesitariamos aqui

2023-05-16 22:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +          <MdClose onClick={() => setIsMenuOpen(false)} />
pienso que podemos agregar cursor: pointer; para dar un toque de accesibilidad a este elemento

2023-05-16 22:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +          <MdMenu onClick={() => setIsMenuOpen(true)} />
pienso que podemos agregar cursor: pointer; para dar un toque de accesibilidad a este elemento

2023-05-18 14:47 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +import { MdMenu, MdClose, MdLogout } from "react-icons/md";
En el momento como es el icono de salida y este NavLink esta fijo pensaría que si, y desde FullscreanNav no tiene como hacerle llegar ese icono para pasarlo por props

2023-05-18 14:47 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +        <Stack direction="column" gap="24px">
Se omite de acuerdo lo validado en el daily

2023-05-18 14:48 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +          <MdClose onClick={() => setIsMenuOpen(false)} />
Resuelto

2023-05-29 15:38 UTC, cmarin001 reviewed
solo se esta contemplando el caso en el que viene mas de un section, pero que sucederia si solo viniese uno? si bien en el codigo esta hecho lo necesario, no existe una historia que contemple ese caso

2023-05-29 15:42 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
>                      {Object.entries(sectionValue.links).map(
resolvamos esto antes de hacer este tipo de recorridos de modo que ese Object.entries puede hacerce a un nivel superior y aqui solo recorrer unicamente el map, ademas de que aqui no necesitamos las entries como tal, con un Object.values seria suficiente

2023-05-29 20:03 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
>                      {Object.entries(sectionValue.links).map(
Resuelto

2023-05-30 13:35 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +                  {Object.values(sectionValue.links).map((linkValue) => (
Aqui tambien tenemos el uso de Object.values, podemos implementar el uso e una funcion como tal o una arrow function donde resolvamos eso   const getValues = (object) => Object.values(object);

2023-05-30 13:35 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +              {Object.values(sectionValue.links).map((linkValue) => (
aqui tambien tenemos lo mismo y podemos resolverlo de ese modo mencionado en el anterior comment

2023-05-30 13:52 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +                  {Object.values(sectionValue.links).map((linkValue) => (
Resuelto

2023-05-30 13:52 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +              {Object.values(sectionValue.links).map((linkValue) => (
Resuelto

2023-05-31 23:51 UTC, wfercanas requested changes

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +  const FullscreenMenu = () => {
Aquí está crando un componente de react dentro de otro componente. Esto no es una buena práctica. 

Ver estas secciones en la documentación de React:
[Nesting and organizing components](https://react.dev/learn/your-first-component#nesting-and-organizing-components)
[Different components at the same position reset state](https://react.dev/learn/preserving-and-resetting-state#different-components-at-the-same-position-reset-state)

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +  const isActive = (url) => currentUrl.startsWith(url);
Esta evaluación tiene sentido cuando estamos en desktop y se puede prender un Link del nav para que el usuario vea en ese momento en dónde está.

Como aquí es un nav emergente, no tiene sentido prender un elemento del menú, pues no hay nada más que mostrar salvo el nav a pantalla completa.

Por lo tanto, sobra el uso de `useLocation()` y sobra la pasada de props de `isActive`

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +  const renderMenu = document.getElementById(portalId);
Renombremos a `node`

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +  const renderMenu = document.getElementById(portalId);
Esta operación puede retornar null si no se encuentra ningún nodo con ese nombre. Hay que controlar la operación y hacer un throw del error.

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/stories/FullscreenNav.Default.stories.jsx
> +        section: "Administrative",
En `<Nav />` acordamos que ibamos a ponerle de nombre "name"

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +      {!isMenuOpen ? (
Esta ternaria no es necesaria, el menú de hamburguesa se debe mostrar siempre. Lo que sí hay es que evaluar el estado del menu para ver si abre el portal por encima de "root" y ahí sí pintar el componente correspondiente.

Es suficiente con
```js
 {isMenuOpen && createPortal(/*...*/)}
```

2023-05-31 23:51 UTC, wfercanas commented on src/components/navigation/FullscreenNav/index.jsx
> +          <MdMenu onClick={() => setIsMenuOpen(true)} />
Este menú hamburguesa es de 24px en los mockups

2023-06-01 19:34 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +  const FullscreenMenu = () => {
Resuelto

2023-06-01 19:34 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +  const isActive = (url) => currentUrl.startsWith(url);
Resuelto

2023-06-01 19:39 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +          <MdMenu onClick={() => setIsMenuOpen(true)} />
Resuelto

2023-06-01 19:39 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +      {!isMenuOpen ? (
Resuelto

2023-06-01 19:39 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/stories/FullscreenNav.Default.stories.jsx
> +        section: "Administrative",
resuelto

2023-06-01 19:39 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +  const renderMenu = document.getElementById(portalId);
Resuelto

2023-06-01 19:39 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +  const FullscreenMenu = () => {
Resuelto

2023-06-05 13:54 UTC, cmarin001 reviewed
no esta funcionando el select para cada item
![image](https://github.com/selsa-inube/design-system/assets/45011420/698e2ea4-2885-4fbf-8fda-fb27d2ded67f)

2023-06-05 15:09 UTC, Andresbl123 commented
En este caso no sería necesario que el item quede seleccionado, ya que como este componente es es para móvil (tablet & móvil), al darle click, el va hacer el redireccionamiento al `path` pasado, por lo cual el componente se desmonta y no se vería que fue seleccionado.

2023-06-06 15:14 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +      {Object.keys(navigation.sections).length > 1 ? (
para este punto podemos implementar algo como   `const totalSections = Object.keys(navigation.sections).length;` de modo que quede un tanto mas limpio

2023-06-06 17:08 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +const FullscreenMenu = ({ navigation, logoutPath, onClose }) => {
Resuelto

2023-06-06 17:08 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +      {Object.keys(navigation.sections).length > 1 ? (
No se si sea necesario crear una contante para esto, a la final solo se necesita para realizar una validación simple en un lugar específico, por lo que me parece que queda más directa de esta forma  y no creamos un espacio en memoria que solo utilizamos una vez.

2023-06-06 21:28 UTC, cmarin001 commented on src/components/navigation/FullscreenNav/index.jsx
> +      {totalSections.length > 1 ? (
esta haciendo obteniendo un doble length lo cual causa que la secciones no aparezcan 
![image](https://github.com/selsa-inube/design-system/assets/45011420/3c06a809-b92b-44cb-8c5b-bd865e420ffb)

2023-06-06 21:41 UTC, Andresbl123 commented on src/components/navigation/FullscreenNav/index.jsx
> +      {totalSections.length > 1 ? (
Resuelto

2023-06-06 22:12 UTC, wfercanas approved these changes

2023-06-06 22:13 UTC, merged