Develop the `<ProgressBar />` component
selsa-inube/design-system pull request #134
Opened 2023-05-16 00:23 UTC by cmarin001

The use that is needed right now for the <ProgressBar /> is when the progress bar is decreasing its width during an interval of time until it disappears (countdown). This is useful to signal that a window or process is running out of time and in practice, it will be used inside the <SectionMessage /> component.

2023-05-16 15:37 UTC, Andresbl123 commented on src/components/feedback/ProgressBar/index.jsx
> +  useEffect(() => {
no se si sea necesario este hook de `useEffect``, creo que hace más complejo de lo que en realidad podría ser, porque, validamos que exista el componente, y no se si esto nos puedo generar un error cuando el usuario importe el componte y le asigne un atributo `id`, luego agrega un event listener al elemento progressBarElement para escuchar el evento de finalización de animación  y así para la función de limpieza, generando un renderizado cada vez que, cambie el valor de lo que hay en array de dependencia, para evitarnos esto, podríamos utilizar el evento `onAnimationEnd` que me permite ejecutar un función una vez termina una animación css, dentro del styled component `StyledProgressBar`

2023-05-16 19:43 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +  useEffect(() => {
resuelto

2023-05-16 20:25 UTC, cmarin001 commented on src/components/feedback/ProgressBar/styles.js
> +    transform: scaleX(0);
resuelto

2023-05-16 21:28 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +const isValidCssPixelMeasure = (element) => {
resuelto

2023-05-17 14:11 UTC, Andresbl123 commented on src/components/feedback/ProgressBar/index.jsx
> +          animationInProgress={!animationComplete}
Esta props nunca se le pasa, asumiría que es para darle estilo al componente, pero en archivo de estilos tampoco se utiliza, y al quitar el `useState`, no creo que sea necesaria

2023-05-17 14:11 UTC, Andresbl123 commented on src/components/feedback/ProgressBar/styles.js
> +  transform-origin: right;
La animación de `<ProgresBar />` en el momento es de derecha a izquierda, aquí esta en forma invertida

2023-05-17 14:57 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +  const [animationComplete, setAnimationComplete] = useState(false);
resuelto

2023-05-17 14:57 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +          animationInProgress={!animationComplete}
resuelto

2023-05-17 15:37 UTC, Andresbl123 commented on src/components/feedback/ProgressBar/index.jsx
> +  const handleAnimationEnd = () => {
Que pena con sumercé olvide mencionarlo, al utilizar el event `onAnimationEnd`, esta función ya no es necesaria, podemos pasar directamente la función que le llega en la props `handleCountdownEnd`, a la final aquí `handleAnimationEnd()` estamos validando si la función viene, ejecútela, cosa que pasaría igual que `onAnimationEnd={handleCountdownEnd}`

2023-05-17 15:58 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +  const handleAnimationEnd = () => {
resuelto

2023-05-17 17:31 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-18 16:23 UTC, wfercanas requested changes

2023-05-18 16:23 UTC, wfercanas commented on src/components/feedback/ProgressBar/index.jsx
> +const defaultDurations = 1000;
1. Dejémoslo en singular "defaultDuration"
2. Aumentemos a 3000, porque pasa muy rápido.

2023-05-18 16:23 UTC, wfercanas commented on src/components/feedback/ProgressBar/index.jsx
> +const ProgressBar = (props) => {
Creo que extender este mismo componente a otros escenarios donde no sea un countdown sino al revés puede ser enrredado.
Entonces, sugiero que cambiemos el nombre del componente a `<CountdownBar />` y más bien si en el futuro realmente necesitamos una barra progresiva, ahí hacemos otro componente quizá con otras props.

Nota: hablar con Leonardo para ajustar en figma.

2023-05-18 16:23 UTC, wfercanas commented on src/components/feedback/ProgressBar/styles.js
> +  }
Este valor al 50% sobra, con el 0% y el 100% basta. Sobre todo si en animation le define que la animación es linear.

2023-05-18 19:42 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +const defaultDurations = 1000;
resuelto

2023-05-18 19:52 UTC, cmarin001 commented on src/components/feedback/ProgressBar/index.jsx
> +const ProgressBar = (props) => {
resuelto

2023-05-18 20:49 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-22 16:10 UTC, merged