Implement the `validateCssSpacing()` function at the general level for the application
selsa-inube/design-system pull request #140
Opened 2023-05-19 16:52 UTC by Andresbl123

Implement the `validateCssSpacing()` function at the general application level. The `validateCssSpacing()` function is responsible for validating CSS spacing according to certain set criteria. This implementation will allow us to use this function throughout the application, ensuring valid spacing in different CSS components and elements.

2023-05-19 20:35 UTC, cmarin001 commented on src/utils/validateCssSpacing.js
> +const validateCssSpacing = (element) => {
se implemento la funcionalidad, sin embargo hay valores que puede tomar que no estan contemplados aqui por ejemplo ["inherit", "initial", "unset", "auto"]

2023-05-19 20:35 UTC, cmarin001 commented on src/components/inputs/TextField/index.jsx
> +  const transformedReadOnly = typeof readOnly === "boolean" ? readOnly : false;
esta caracteristica no deberia estar incluida aqui, ya que para eso cada issue tiene su tarjeta

2023-05-19 20:35 UTC, cmarin001 commented on src/components/inputs/TextField/index.jsx
> +      readOnly={transformedReadOnly}
lo mismo aplica para aqui, ademas en la especificacion solo contemplaba que fuera <Text/> quien implementara la funcionalidad de **validateCssSpacing** y no se mencionaba la implementacion del readOnly

2023-05-19 21:08 UTC, cmarin001 commented on src/utils/validateCssSpacing.js
> +/**it is validated that the values entered are in pixels and valid according to the css property margin and padding. */
adicionalmente creo que deberiamos de renombrar el directorio donde se encuentra validateCssSpacing de modo que se llame **utilities** de este modo evitamos inconsistencias con el directorio contenido dentro de components que se llama **utils**

2023-05-23 20:08 UTC, wfercanas requested changes

2023-05-23 20:08 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  const isGlobalCssValue =
Aquí hace una validación que bien podría determinar un return temprano de la función. Sin embargo, pospone el return y el resultado queda condicionado a un ||.

Si la condición resulta concluyente ejecute el return y no posponga el resultado.

2023-05-23 20:08 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  if (size === "" || splitPixels.length === 0 || splitPixels.length > 4) {
Esta validación podría ir de primeras y nos ahorramos crear variables innecesariamente.

2023-05-24 15:59 UTC, wfercanas requested changes

2023-05-24 15:59 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
La función estaría retornando true o false según se pasan o  no las validaciones. Lo que significa que en los distintos componentes se obtiene uno de estos dos valores y si es true, entonces se sigue con las demás tareas por hacer.

Sin embargo, si el desarrollador usa mal las props padding o margin de un componente y la idea es que aparezca un error parecido al que aparece vía prop-types, el componente tendría que recibir el false de esta función y encargarse del error.

No creo que sea lo adecuado, lo mejor sería que esta función evalúe y si hay un error, se encargue de disparar el error.

2023-05-24 15:59 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  if (size === "" || splitPixels.length === 0 || splitPixels.length > 4) {
Según el comentario que hice de encargarnos del error, este ID habría que partirlo en tres.

2023-05-24 15:59 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  const isGlobalCssValue = globalValuesPropertiesCss.includes(size);
Esta asignación o creación de variable tiene sentido sólo si length es igual a 1. Sería mejor que estuviera dentro de un if

2023-05-25 16:17 UTC, wfercanas requested changes

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +      "if the input argument is not passed, the component will take the default value"
Ese mensaje de warning puede ser más preciso, por que le va a tocar al desarrollador ver la secuencia de tareas del stack para ver en qué archivo y fila fue que se originó el mensaje y luego revisar cuál es la validación que está haciendo.
Es preferible decir que si define una propiedad de box model con un string vacío el componente va a tomar el valor que tenga por defecto la propiedad.

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +const validateCssSpacing = (size) => {
Renombremos a `validateBoxModelMeasure()`

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  const splitPixels = size.trim().split(" ");
Renombremos a `measures`

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  const splitPixels = size.trim().split(" ");
La operación `trim()` se puede hacer siempre que size sea string. Hay que hacer esa validación primero.

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +  if (splitPixels.length === 0 || splitPixels.length > 4) {
Si arriba se valida que `size` sea un string, entonces `measures` será por lo menos de longitud 1, ya que aunque sea guardará un string vacío.
Dejar entonces la validación si es mayor a 4 y decir explícitamente que la longitud no puede ser mayor a 4.

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +const globalValuesPropertiesCss = ["inherit", "initial", "unset", "auto"];
Renombremos por `nonPixelValues`

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +const validateCssSpacing = (size) => {
Cambiemos `size` por `value`

2023-05-25 16:17 UTC, wfercanas commented on src/utilities/validateCssSpacing.js
> +    return false;
Este último else es escribir un error y retornar un false porque por alguna razón no pasó por los condicionales positivos.

Esto vuelve e implica que el componente recibe ese false y debe decidir qué hacer con eso. Quizá esta función de validación no debería retornar boolean sino ser un undefined. Es decir, no se espera que devuelva nada, peeero, si una validación se revienta deberíamos hacer un throw de un error.

Con lo anterior, el componente que usa la validación debe hacer un `try ... catch` e imprimir el error dentro del catch.

**Conclusión**: cambiemos los `return true` por simples `return`, mientras que los errores se vuelven throw new Error()

2023-05-25 19:43 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +      "if the input argument is not passed, the component will take the default value"
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +const validateCssSpacing = (size) => {
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +  const splitPixels = size.trim().split(" ");
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +  if (splitPixels.length === 0 || splitPixels.length > 4) {
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +const globalValuesPropertiesCss = ["inherit", "initial", "unset", "auto"];
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +const validateCssSpacing = (size) => {
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +  } else if (splitPixels.every((valueSize) => regex.test(valueSize))) {
Resuelto

2023-05-25 19:44 UTC, Andresbl123 commented on src/utilities/validateCssSpacing.js
> +    return false;
Resuelto

2023-05-29 15:40 UTC, wfercanas requested changes

2023-05-29 15:40 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +    : defaultMargin;
En este caso validateBoxModelMeasure no devuelve un boolean, por lo que no puede pasarlo así a una ternaria. Si edita el valor en storybook va a ver que la historia se rompe.
Tiene que usar un `try...catch` y manejar el error si ocurre.

2023-05-29 17:01 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +    : defaultMargin;
Resuelto

2023-05-29 19:26 UTC, cmarin001 commented on src/components/data/Text/index.jsx
> +    : defaultMargin;
si bien se resuelve el problema previamente planteado, el codigo tiene ciertos puntos que podemos mejorar para empezar estamos presentando ciertos lios con la complejidad ciclomatica (https://mpijierro.medium.com/complejidad-ciclom%C3%A1tica-y-como-reducirla-7374c215f666), podemos considerar un enfoque un tanto diferente como tal vez este seria uno a considerar https://www.youtube.com/watch?v=0NlsJuwFsrQ

2023-05-30 15:38 UTC, wfercanas requested changes

2023-05-30 15:38 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  };
Las funciones transformedMargin y transformedPadding se pueden consolidar en una sola. Puede crear la función transformedMeasure, que reciba como parámetro tanto el measure como defaultMeasure.

De esa manera al llamar la función, se vería algo como: `transformedMeasure(padding, defaultPadding);`

2023-05-30 15:38 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +      return padding;
Este return puede dejarlo después del `try ... catch`, no dentro del try.

2023-05-30 15:38 UTC, wfercanas commented on src/components/data/Text/index.jsx
>    align: PropTypes.oneOf(alignsOptions),
Aprovechemos para corregir este english... sería `alignOptions`

2023-05-30 16:17 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +  };
Resuelto

2023-05-30 16:17 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +      return padding;
Resuelto

2023-05-30 16:18 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
>    align: PropTypes.oneOf(alignsOptions),
Resuelto

2023-05-30 21:20 UTC, wfercanas approved these changes

2023-05-30 21:20 UTC, merged