Fix the font-weight property in `<TextField /> styles
selsa-inube/design-system pull request #141
Opened 2023-05-19 21:04 UTC by cmarin001

This proposed pull request is intended to address the discrepancy in the 'font-weight' attribute. Presently, the value is set at 500, which is inconsistent with the design mockups. According to the latter, the 'font-weight' should be set to 400. The successful execution of this pull request will ensure conformity with the design specifications.

2023-05-19 22:19 UTC, Andresbl123 commented on src/components/inputs/TextField/styles.js
> +  font-weight: ${typography.sys.typescale.bodyLarge.weight.regular};
En este caso, el valor aquí proporcionado no existe, por lo tanto, devuelve `undefined`. Esto se debe a que no hay propiedades dentro de `weight`. Además, en el token de tipografía `bodyLarge`, el valor asignado a la propiedad `font-weight` es de 500, por lo tanto, no podemos asignarle ese valor. En su lugar, debemos recurrir al token ref, donde sí podemos acceder a `weight.regular`

2023-05-19 23:49 UTC, cmarin001 commented on src/components/inputs/TextField/styles.js
> +  font-weight: ${typography.sys.typescale.bodyLarge.weight.regular};
resuelto

2023-05-23 17:25 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-23 19:45 UTC, wfercanas requested changes

2023-05-23 19:45 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  font-weight: ${typography.ref.typeface.weight.regular};
Deberíamos usar los token de sistema en lugar del de referencia. Veo que hay diferencias entre lo que está en el textfield y lo que está en foundations-typography, así que hay que revisar con Leonardo para garantizar que se use lo que esté definido en foundations como system token

2023-05-23 20:01 UTC, cmarin001 commented on src/components/inputs/TextField/styles.js
> +  font-weight: ${typography.ref.typeface.weight.regular};
resuelto

2023-05-23 20:11 UTC, Andresbl123 commented
cumple con los requerimientos

2023-05-23 20:35 UTC, wfercanas approved these changes

2023-05-23 20:37 UTC, merged