Fix <breadCrumb/> redirection in mobile devices
selsa-inube/design-system pull request #147
Opened 2023-05-24 23:36 UTC by cmarin001

2023-05-25 00:13 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-25 15:53 UTC, wfercanas requested changes

2023-05-25 15:53 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +  const menuRef = useRef(null);
Esta versión con doble referencia me parece que se pone compleja. Prefiero que intentemos lo siguiente:
1. La referencia de containerRef moverla del hermano de `<Label>` a el `<StyledRelativeContainer>` que envuelve todo el componente Ellipsis.
2. Como ubicamos la referencia lo más global posible, vamos a contar que el evento click burbujee (bubbling) hasta ese contenedor.
3. Renombremos la función `handleClickOutside()` por `closeEllipsisMenu()`
4. Por dentro de esta función, sólo hagamos:

```js
  const closeEllipsisMenu = (event) => {
    if (!containerRef.current.contains(event.target)) {
      setShowMenu(false);
    }
  };
```

2023-05-25 15:53 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
> +          handleClick={handleEllipsisClick}
Cambiemos el nombre de `handleEllipsisClick` por `toggleEllipsisMenu`

2023-05-25 15:53 UTC, wfercanas commented on src/components/navigation/BreadcrumbEllipsis/index.jsx
En los eventListener, usemos `click` en lugar de `mousedown". Con click incluye el touch en mobile con el dedo, con mousedown podemos tener problemas.

2023-05-25 15:53 UTC, wfercanas commented on src/components/navigation/BreadcrumbMenu/index.jsx
> +const BreadcrumbMenu = React.forwardRef((props, ref) => {
Quizá con los cambios planteados en el control de la propagación de evento no necesitemos estas referencias.

2023-05-25 15:53 UTC, wfercanas commented on src/components/navigation/BreadcrumbMenu/index.jsx
> +            onClick={handleClick}
Aqui estamos intentando pasarle desde el Breadcrumbs hasta el Link la capacidad de cerrar el Menu. Quizá no valga la pena si estos son links que redirigen al usuario a otra página y al final del día los componentes se van a desmontar.

2023-05-26 14:44 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-05-29 15:22 UTC, wfercanas approved these changes

2023-05-29 15:22 UTC, merged