Fix `<Tabs/>` in order to add a right-padding
selsa-inube/design-system pull request #148
Opened 2023-05-24 23:50 UTC by Andresbl123

An issue related to the `<Tabs /> ` component has been addressed. In the current implementation, when passing a list of tabs to the component, the first `<Tab /> ` has padding on the left, which is correct. However, when the screen is tablet or mobile sized, the last `<Tab />` is displayed close to the right edge of the tab container, which is undesirable. The aim of this PR is to solve this problem by ensuring that the last tab also has proper padding on the right.

2023-05-24 23:57 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-05-25 15:25 UTC, wfercanas requested changes

2023-05-25 15:25 UTC, wfercanas commented on src/components/navigation/Tabs/styles.js
> +    padding-right: 16px;
Aquí le estamos delegando al responsabilidad del espacio a la derecha a un elemento interno de la lista, no a la lista en sí. Es preferible que sea la lista la que se haga cargo.
Si revisa, el layout de los flex items se rompe en el último elemento:
![image](https://github.com/selsa-inube/design-system/assets/36939686/e898869f-888d-45be-8a72-d03e02fcca5f)

2023-05-29 15:09 UTC, cmarin001 commented on src/components/navigation/Tab/styles.js
> +  padding: 0px 16px;
para este caso no es la solucion, si bien agrega un padding hacia la derecha se esta aplicando por cada tab ocasionando asi que el diseno no este alineado con lo que hay en figma

2023-05-29 15:10 UTC, cmarin001 commented on src/components/navigation/Tabs/styles.js
> -  padding: 0px 16px;
debemos explorar y lograr que el cambio se aplique desde el contenedor general ya que si no es asi el cambio se va a aplicar por cada elemento dentro de tabs generando una separacion adicional que no es lo que buscamos

2023-05-29 16:23 UTC, Andresbl123 commented on src/components/navigation/Tabs/styles.js
> -  padding: 0px 16px;
Resuelto

2023-05-29 16:23 UTC, Andresbl123 commented on src/components/navigation/Tab/styles.js
> +  padding: 0px 16px;
Resuelto

2023-05-29 19:19 UTC, cmarin001 commented on src/components/navigation/Tabs/styles.js
> +    padding-right: 16px;
esto aun no ha sido resuelto

2023-05-30 13:20 UTC, cmarin001 commented on src/components/navigation/Tabs/styles.js
> +    padding-right: 16px;
resuelto

2023-05-30 15:20 UTC, wfercanas approved these changes

2023-05-30 15:21 UTC, wfercanas requested changes

2023-05-30 21:15 UTC, wfercanas approved these changes

2023-05-30 21:16 UTC, merged