Cm/3494/colors palette
selsa-inube/design-system pull request #37
Opened 2023-01-19 13:07 UTC by M3rlin00

se agregó la paleta de colores y el componente para visualizarla en funcionamiento

2023-01-19 17:17 UTC, wfercanas requested changes

2023-01-19 17:17 UTC, wfercanas commented on src/shared/colors/stories/Colors.stories.js
> +  title: "Design System/Colors",
Reemplazar "title: Design System/Colors" por "Shared/Colors".

2023-01-19 17:17 UTC, wfercanas commented on src/shared/colors/stories/Colors.stories.js
> +};
Separemos las historias. En lugar de tener Primary, creemos Reference y System.
En el de Reference dejamos las cards y en System dejamos la tabla.

2023-01-19 17:17 UTC, wfercanas commented on package.json
> +    "@ctrl/tinycolor": "^3.5.0",
No creo que aguante incluir una dependencia adicional sólo para el uso de isDark(). Podemos dejar la card sin el Lorem Ipsum por ahora.

2023-01-19 17:17 UTC, wfercanas commented on src/shared/colors/stories/index.jsx
> +const Colors = (dataColors) => {
Partamos este componente en varios más pequeños:

- [ ] Un componente con la card de color.
- [ ] Un componente con la grilla que hace un map dentro de un tipo de color (ej: purple) y retorna la grilla con los componentes card en el map.
- [ ] Un componente preferiblemente con `display: flex; flex-wrap: wrap` y que haga un map de todos los tipos de color y retorne dentro del map la grilla anterior.
- [ ] Un componente para la tabla

2023-01-19 22:49 UTC, M3rlin00 commented on src/shared/colors/stories/Colors.stories.js
> +  title: "Design System/Colors",
se corrigio la incidencia

2023-01-19 22:49 UTC, M3rlin00 commented on src/shared/colors/stories/Colors.stories.js
> +};
se corrigio la incidencia

2023-01-19 22:49 UTC, M3rlin00 commented on package.json
> +    "@ctrl/tinycolor": "^3.5.0",
se corrigio la incidencia

2023-01-19 22:50 UTC, M3rlin00 commented on src/shared/colors/stories/index.jsx
> +const Colors = (dataColors) => {
se corrigio la incidencia, sin embargo, hay un tema con la recomendacion de usar flex en lugar de grid con la cual tengo ciertas dudas

2023-01-26 16:50 UTC, wfercanas requested changes

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/styles.js
> +  margin: 0 0 10px 0;
Este `margin` no debería estar. La vez pasada acordamos que el espaciado entre cards lo define la grilla, no la card. En la grilla usamos `row-gap`.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +          <label htmlFor="name">Name</label>
Los `label` deberíamos dejarlos para trabajar junto con los `input`. Aquí como no hay ningún `input` ese **htmlFor** no funciona.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="name">{token}</span>
Aquí habría que eliminar ese **id** si este no es dinámico. Puesto que como este es un componente que va a estar dentro de un map, todos los nodos dentro del array que retorna el map van a tener el mismo **id**, cosa que va en contra del hecho de que los **id** no se deben repetir dentro de un documento HTML.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="hex">{colors.ref.palette[props.color][props.token]}</span>
Los mismos comentarios sobre el `label` y el `id` aplican es estas dos últimas líneas.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="hex">{colors.ref.palette[props.color][props.token]}</span>
Si ya a la entrada del componente destructuró las variables `color` y `token` de lo que se recibe vía `props`, no hace falta usar aquí `props.color` o `props.token`.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +const ColorReference = (dataColors) => {
Colocar como parámetro `dataColors` puede ser un poco confuso. Aunque uno puede colocarle cualquier nombre a los elementos que recibe como parámetro un componente de React, lo estándar es usar la palabra `props`.
Luego de eso, se desestructuran las variables que vienen dentro de las `props`, que para el caso de este componente es lo que le va a pasar como props desde la historia de Storybook.

Si miramos esa historia, le pasa por {...args} la prop `colors`, que tiene por dentro el objeto `colors` con los tokens.

**Conclusión**: usar el estándar de `props`, desestructurar de allí la variable `colors`, que contiene el objeto `colors` y usar directamente la variable `colors` dentro del **Object.keys()**.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +      {Object.keys(dataColors.colors.ref.palette).map((color) => (
Este Object.keys() devuelve un array con algo como ["darkNeutral", "midNeutral", "lightNeutral", ...]. Con el fin de ser más preciso en el uso del lenguaje aquí, llamemos a estos strings "colorGroup". Es decir, cuando hablemos de un colorGroup estamos hablando de todos los colores del grupo "darkNeutral" o todos los colores del grupo "red".

En ese orden de ideas, el map que hacemos aquí lo podemos escribir como `.map((colorGroup) => (....))`.

Finalmente, a `<GridColor>` no le pasaríamos `color` como prop, sino `colorGroup`.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +          <CardColor key={token} color={key} token={token}></CardColor>
`<CardColor />` puede ir auto-cerrado.

2023-01-26 16:50 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +      {Object.entries(colorPalette).map(([key, value]) =>
Este proceso para llegar a los colores está más complicado de lo necesario. Me explico:

- Cuando crea `colorPalette`, está creando un objeto que tiene sólo una llave y un valor (valor que es igual a un objeto con colores).
- Luego, cuando hace `Object.entries()` está obteniendo un array de length = 1 (Puesto que `colorPalette` sólo tiene 1 llave). Dentro de la posición cero de ese array de length = 1 tiene otro array, uno como este: ["darkNeutral", {...}].
- A ese array de una posición le hace un `map`, es decir, un map de una sola iteración.
- En esa única iteración extrae la `key` y el `value`, pero esos valores ya los tenía, porque con esos valores fue que armó el objeto `colorPalette` (la prop `color == key` y `colors.ref.palette[color] == value`).
- Luego con esos mismos valores hace un `Object.keys(value)` que es igual a obtener un array con los colores de un grupo de colores (es decir, si el grupo de colores es "darkNeutral", ese array contiene los colores de ese grupo: ["dn100", "dn200", ...].
- Con ese array de colores hace otro `map` (este sí que tiene mucho sentido) para poder recorrer esos nombres de colores y obtener los hexadecimales.

**Conclusión**: Toda la parte del `Object.entries` dentro del `return` sobra. La clave es que antes de llegar al `return` usted ya haya logrado obtener el array de colores, de esa manera el return es breve de leer, porque es sólo un map y sale.

2023-01-26 19:33 UTC, M3rlin00 commented on src/shared/colors/stories/reference/styles.js
> +  width: 160px;
incidencia resuelta 
[](https://github.com/selsa-inube/design-system/commit/0c1c91b2f8ec16e2f701c85382fde0ddff1afd28)

2023-01-26 19:37 UTC, M3rlin00 commented on src/shared/colors/stories/reference/styles.js
> +  margin: 0 0 10px 0;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/0c1c91b2f8ec16e2f701c85382fde0ddff1afd28)

2023-01-26 19:38 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="name">{token}</span>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/0c1c91b2f8ec16e2f701c85382fde0ddff1afd28)

2023-01-26 19:38 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="hex">{colors.ref.palette[props.color][props.token]}</span>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/0c1c91b2f8ec16e2f701c85382fde0ddff1afd28)

2023-01-26 19:39 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +          <span id="hex">{colors.ref.palette[props.color][props.token]}</span>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ff63df77c13649427e578039c0d5f113e7893bf6)

2023-01-26 19:40 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +const ColorReference = (dataColors) => {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ff63df77c13649427e578039c0d5f113e7893bf6)

2023-01-26 19:41 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +      {Object.keys(dataColors.colors.ref.palette).map((color) => (
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ea074bfd00904ba568e4e4fab207bec89aaf292a)

2023-01-26 19:43 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +          <CardColor key={token} color={key} token={token}></CardColor>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/995c357aa7dc8c9ecc5bb4ac8e79ff7cb4329a90)

2023-01-26 19:44 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +      {Object.entries(colorPalette).map(([key, value]) =>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/70bfecff315d5b07f5b40ed2d925286c76bacf91)

2023-01-30 15:06 UTC, wfercanas requested changes

2023-01-30 15:06 UTC, wfercanas commented on src/shared/colors/stories/system/styles.js
> +  border: 1px solid #b3bac5;
Cambiar estos colores hexadecimales por tokens.

2023-01-30 16:44 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +        <GridColor key={colorGroup} colorGroup={colorGroup} />
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/e8a263400b029d1367e166330e806bb0812792f7)

2023-01-30 17:12 UTC, M3rlin00 commented on src/shared/colors/stories/reference/styles.js
> +  border: 1px solid #000000;
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/1deb1a65de34cd1ac1b93ac5e3bdea96a87cf869)

2023-01-30 17:13 UTC, M3rlin00 commented on src/shared/colors/colors.js
> + */
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/1deb1a65de34cd1ac1b93ac5e3bdea96a87cf869)

2023-01-31 15:41 UTC, wfercanas requested changes

2023-01-31 15:41 UTC, wfercanas commented on src/shared/colors/stories/reference/index.jsx
> +  const { colors } = props;
En este archivo estamos creando la variable colors tanto al hacer el `import { colors } from '../colors'` como al destructurar las props aquí en `<ColorReference />`.

Dado que los componentes aquí creados pueden ir directamente al colors importado, sobraría recibir el mismo objeto por props en `<ColorReference />`. Así que podríamos quitar esta destructuración de aquí y en la historia de Storybook tampoco haría falta pasarle por props un objeto al cual el componente puede acceder directamente siempre.

Ventajas: además de simplificar el código, sabemos siempre cuál es el objeto que está usando. Si lo dejamos como está a veces usa el de las props y a veces el import.

2023-01-31 15:41 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +  const { colors } = props;
Aquí también aplica el hecho de usar el colors del import y no este import de las props. Por lo tanto, hay que eliminar esta destructuración y la pasada de colors desde la historia de Storybook con las args.

2023-01-31 15:41 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +  return systemTokensList.map(([role, systemTokensGroup]) => (
Todo este `return` podría extraerse a un componente aparte que se encarge que recibir un `role` por props y con eso ya este componente podría armar la tabla/grilla de tokens.

De hecho este componente puede llamar por dentro a `<Field />` para pintar cada fila.

**En conclusión**, `<SystemReference />` podría hacer un map en el que por cada role devuelve este componente nuevo.

2023-01-31 15:41 UTC, wfercanas commented on src/shared/colors/stories/system/styles.js
> +  &: last-child {
Aquí el operador va pegado: `&:last-child`

2023-01-31 15:41 UTC, wfercanas commented on src/shared/colors/stories/system/styles.js
> +  justify-content: space-around;
Usar flex aquí le complica la presentación de los tokens, porque como hay unos con nombres largos y otros cortos, las columnas no le quedan iguales. Unos tokens le van a quedar más a la izquierda y otros más a la derecha (Se nota más en los divs que muestran los hexadecimales).

Es preferible usar una grilla donde usted controle el ancho de las columnas. Así quedan todas iguales. Luego, dentro de cada columna, usted puede indicar que quiere el contenido centrado y así las tablas se ven más organizadas.

2023-01-31 15:55 UTC, wfercanas requested changes
Aparte de los comentarios en el código, hace falta integrar lo que ya está en main respecto de la fuente, por lo que le sugiero que:

1. Se pase a la rama main: `git switch main`
2. Actualice su rama main local: `git pull`
3. Se pase a la rama feature: `git switch ab/....`
4. Haga un merge de main en la rama feature: `git merge main`

2023-01-31 20:56 UTC, M3rlin00 commented on src/shared/colors/stories/reference/index.jsx
> +  const { colors } = props;
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/cf4e3697239d69c5554d6c3bd53470d51e508729)

2023-01-31 20:56 UTC, M3rlin00 commented on src/shared/colors/stories/system/index.jsx
> +  const { colors } = props;
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/cf4e3697239d69c5554d6c3bd53470d51e508729)

2023-01-31 20:56 UTC, M3rlin00 commented on src/shared/colors/stories/system/styles.js
> +  &: last-child {
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/2505f2738b9ec3228a4c97a6af6818c18f3054b2)

2023-01-31 20:57 UTC, M3rlin00 commented on src/shared/colors/stories/system/styles.js
> +  justify-content: space-around;
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/1a96ea289a6261800e1c29484c370fc4e5f17d13)

2023-02-01 16:26 UTC, wfercanas requested changes

2023-02-01 16:26 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +        <Field role={role} systemTokensGroup={systemTokensGroup}></Field>
En lugar de pasarle todo el array de tokens del grupo, podríamos hacer aquí el map de cada uno de los grupos. De tal manera que `<Field />` es solamente responsable de una fila específica de la tabla, no de renderizar todas las filas.

Para que `<Field />` haga este trabajo entonces ya no necesita todo el array sino `<Field role={role} systemToken={systemToken} />`

2023-02-01 16:26 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +  const colorReference = colors.ref;
Creo que agregar estas variables (systemTokens y colorReference) sobra, toda vez que todos los componentes tienen acceso a `colors.sys` o `colors.ref`.

2023-02-01 16:26 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +function getKeyByValue(obj, value) {
Entendí después de leer el código que el propósito de esta función es hallar el token de referencia para un hexadecimal específico.

Si es así, y como esta función es sólo para uso de esta documentación, podríamos renombrar la función a algo como "getRefTokenFromHex" y que la función sólo reciba el hexadecimal. El objeto no es necesario porque este es color.ref y ya tiene acceso vía scope.

2023-02-01 20:37 UTC, M3rlin00 commented on src/shared/colors/stories/system/index.jsx
> +  const systemTokensList = Object.values(systemTokensGroup);
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/047abeb277724d3bfa81da11bfbc24b6ba04611d)

2023-02-01 20:37 UTC, M3rlin00 commented on src/shared/colors/stories/system/index.jsx
> +        <Field role={role} systemTokensGroup={systemTokensGroup}></Field>
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/047abeb277724d3bfa81da11bfbc24b6ba04611d)

2023-02-01 20:37 UTC, M3rlin00 commented on src/shared/colors/stories/system/index.jsx
> +function getKeyByValue(obj, value) {
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/cc63f76372f3ef48e141d556c6eb662ab6b86099)

2023-02-01 20:38 UTC, M3rlin00 commented on src/shared/colors/stories/system/index.jsx
> +  const colorReference = colors.ref;
incidencia resuelta 
[commitResolver](https://github.com/selsa-inube/design-system/commit/cc63f76372f3ef48e141d556c6eb662ab6b86099)

2023-02-01 21:28 UTC, wfercanas requested changes

2023-02-01 21:28 UTC, wfercanas commented on src/shared/colors/stories/system/index.jsx
> +          ></Field>
Dejar el <Field /> autocerrado.

2023-02-01 22:03 UTC, wfercanas approved these changes

2023-02-01 22:58 UTC, merged