Ab/3568/blanket component
selsa-inube/design-system pull request #42
Opened 2023-01-25 16:59 UTC by Andresbl123

"Blanket" component that is used to hide or show a dark layer on the screen. The component uses React state to control the visibility and clickability outside the component. The component's history is implemented

2023-02-06 21:33 UTC, M3rlin00 commented on src/components/utils/Blanket/Blanket.jsx
> +const BlanketComponent = ({ children }) => (
asi esta bien y funciona, sin embargo, considero que de acuerdo a las reviews que fernando nos ha hecho y esto tambien para mejor legibilidad y si en un futuro se necesita agregar mas propiedades quedaria mas ordenado, el parametro que el componente deberia recibir es props y luego deestructurarlo y lo cual quedaria algo como  
const BlanketComponent = ( props ) => (
 const { children } = props;

2023-02-06 21:37 UTC, M3rlin00 requested changes
revisar blanket.jsx

2023-02-06 21:54 UTC, M3rlin00 commented on src/components/Blanket/stories/Blanket.stories.js
> +        "property used to determine if the component is capable of hosting nodes **ReactElement**",
si agrego una propiedad que servira de control desde la historia esta deberia ser capaz de mostrar algun tipo de interaccion desde el storybook desplegado, por que de este modo pues la propiedad logra servir de documentacion pero para alguien que no necesariamente estuvo durante el desarrollo queda un poco perdido

2023-02-07 15:21 UTC, wfercanas requested changes

2023-02-07 15:21 UTC, wfercanas commented on src/components/utils/Blanket/Blanket.jsx
> +import React from "react";
Renombrar el archivo como index.jsx

2023-02-07 15:21 UTC, wfercanas commented on src/components/utils/Blanket/Blanketstyles.js
> +  height: 100%;
Es preferible no mezclar `height` y `width` con `top` y `left`. Sugiero que use `top`, `bottom`, `left` y `right`, todas en cero, para definir el área del blanket.

2023-02-10 20:34 UTC, wfercanas commented on src/components/utils/Blanket/stories/Blanket.stories.js
> +  title: "components/BlanketComponent",
Dejemos mejor sólo utils/Blanket

2023-02-10 20:36 UTC, wfercanas requested changes

2023-02-10 20:36 UTC, wfercanas commented on src/components/utils/Blanket/stories/Blanket.stories.js
> +const BlanketS = (args) => <Blanket {...args} />;
Renombremos la historia como "Default"

2023-02-10 21:11 UTC, wfercanas requested changes
El nombre del archivo le quedó "Blankent", en lugar de "Blanket" (el de storybook)

2023-02-10 21:50 UTC, wfercanas approved these changes

2023-02-10 21:51 UTC, merged