Cm/3567/spinner
selsa-inube/design-system pull request #43
Opened 2023-01-25 22:15 UTC by M3rlin00

Added the spinner-component according to the card #3567

2023-02-03 22:26 UTC, wfercanas requested changes

2023-02-03 22:26 UTC, wfercanas commented on src/components/feedback/Spinner/styles.js
> +const StyledSpinner = styled.div`
Los  `<Spinner />` van a quedar más grandes de lo que deberían porque aquí se está aplicando por defecto la propiedad `box-sizing: content-box`. Es decir, no está incluyendo el border en las medidas del height y el width.

Como en los diseños esos anchos sí están incluyendo el border. Hay que colocar la propiedad `box-sizing: border-box`

2023-02-03 22:26 UTC, wfercanas commented on src/components/feedback/Spinner/styles.js
> +    transform: translate3d(-50%, -50%, 0) rotate(360deg);
En estos transform, sólo es necesario que el `<Spinner />` rote, no que se traslade en 3d. De hecho, si ambos valores del translate3d están iguales, la animación no hace nada.

2023-02-03 22:26 UTC, wfercanas commented on src/components/feedback/Spinner/styles.js
> +  animation-play-state: inherit;
La propiedad animation-play-state funciona para pausar o reanudar una animación desde donde iba. Ese es un comportamiento que no le hemos definido al `<Spinner />`. **Esta propiedad habría que quitarla**.

2023-02-03 22:26 UTC, wfercanas commented on src/components/feedback/Spinner/styles.js
> +        ? colors.ref.palette.lightNeutral.ln50 + "00"
Buena solución para el transparente, sin embargo no es necesario usar dos colores diferentes, puede hacer el .ln200 cuando es false, y ln200 + "00" cuando es true. 

De esa forma se sabe que de todas formas, si algún color llega a ir ahí, es el ln200 y ningún otro.

2023-02-06 17:15 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +  Spinner.propTypes = {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ba781791656c0d71a467bb988b3ed5dbf0d4be4e)

2023-02-06 17:15 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +    ></StyledSpinner>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/72f1dd6ac247b83516080f11ca4d34a475e98e4a)

2023-02-06 17:16 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +const getParent = (colorKey) => {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/8bc5b505848ce6c634edc592cc1f6c28d31d4438)

2023-02-06 17:17 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +const StyledSpinner = styled.div`
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-06 17:18 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +  will-change: transform;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/2d336a181547cd496223029fd7c23c313d218d7b)

2023-02-06 17:18 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +  transform: translate3d(-50%, -50%, 0);
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-06 17:19 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +const StyledSpinner = styled.div`
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-06 17:19 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +    transform: translate3d(-50%, -50%, 0) rotate(360deg);
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-06 17:20 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +  animation-play-state: inherit;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-06 17:20 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +        ? colors.ref.palette.lightNeutral.ln50 + "00"
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e9a8e117db50eaa549fda3b8dcd8b4c2ca5031c0)

2023-02-07 14:46 UTC, wfercanas requested changes
Ya con todas las historias en el archivo, ya parece que queda como muy denso de leer. Son casi 200 líneas y hay diferentes templates, controles y demás.
Creo que convendría crear mejor una carpeta de stories y dentro de esa carpeta crear un archivo para cada historia. Ejemplo: Spinner.Default.stories.js, Spinner.Sizes.stories.js, ...

2023-02-07 14:46 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +  size: PropTypes.string,
3 cosas a revisar en la prop de size:
1. Esta prop es obligatoria, por lo que debemos agregar el isRequired.
2. Si a size le pasamos un string que no tiene que ver con las opciones (por ejemplo "extra-large"), se renderiza un spinner ultra pequeño.
3. El componente tiene un valor default de "medium"

2023-02-07 14:46 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +  isTransparent: PropTypes.bool,
La prop isTransparent tiene un valor `false` por default.

2023-02-07 14:46 UTC, wfercanas commented on src/components/feedback/Spinner/Spinners.stories.js
> +  // border: 1px dotted;
Este comentario sobra en el código

2023-02-07 14:46 UTC, wfercanas commented on src/components/feedback/Spinner/Spinners.stories.js
> +const story = {
Dejemos este objeto en la parte superior del archivo, así es más fácil saber qué contiene este archivo.

2023-02-07 15:06 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +  size: PropTypes.string,
Esta opción de prop-types puede ser útil:

```js
// Puedes asegurar que una prop esta limitada a valores específicos si se
// considera como enum.
  optionalEnum: PropTypes.oneOf(['News', 'Photos']),
```

2023-02-07 21:38 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +  size: PropTypes.string,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ab7ececae9d36273326d5c6e2976c40346c5e68c)

2023-02-07 21:38 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +  appearance: PropTypes.string,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ab7ececae9d36273326d5c6e2976c40346c5e68c)

2023-02-07 21:38 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +  isTransparent: PropTypes.bool,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ab7ececae9d36273326d5c6e2976c40346c5e68c)

2023-02-07 21:39 UTC, M3rlin00 commented on src/components/feedback/Spinner/styles.js
> +  darkNeutral: colors.ref.palette.darkNeutral.dn500,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ab7ececae9d36273326d5c6e2976c40346c5e68c)

2023-02-07 21:39 UTC, M3rlin00 commented on src/components/feedback/Spinner/Spinners.stories.js
> +  // border: 1px dotted;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/a328402d9ff89c82f4c5af277d1f1da861f9a31f)

2023-02-07 21:40 UTC, M3rlin00 commented on src/components/feedback/Spinner/Spinners.stories.js
> +const story = {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9e2c3fa0e6f1469252f749c478e4fb6d3697de3c)

2023-02-08 17:30 UTC, wfercanas requested changes

2023-02-08 17:30 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +const transparentOptions = [true, false];
Hasta aquí está definiendo los posibles valores que puede recibir por props el componente. Le sugiero que a estos objetos les haga un export nombrado, de esa manera:

1. En todos los archivos de historias lo que hace es importar estos objetos y no tiene que repetirlos en cada archivo.
2. Si los valores llegan a cambiar en el futuro, sólo hay que tocarlos en este index.jsx y no aquí y en cada historia.
3. El array de transparentOptions sobraría, es suficiente con controlar que la prop isTransparent es boolean.

2023-02-08 17:30 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +const defaultTransparent = "false";
Si un desarrollador utiliza el componente haciendo sólo `return <Spinner />`, le van a aparecer errores en la consola que dicen algo como: "prop size isRequired but got undefined" (perfecto).

Esto pasa porque el desarrollador no pasó las props y cuando llegamos a la línea donde destructuramos las props, no existen ni size, ni appearance ni isTransparent.

Luego usted lo arregla con las ternarias de más abajo. Cuando pregunta `appearances.includes(appearance) ?` lo que está ocurriendo es que `appearance` se evalúa como `undefined`. Ese valor no está en el array, por lo tanto le aplica el `defaultTransparent`.

En síntesis, estamos permitiendo que las prop de `<Spinner />` puedan ser `undefined`, aún cuando luego arreglemos con ternarias las props que le pasamos al `<StyledSpinner />`.

**Arreglo:** para que esto no pase y no tengamos que arreglar manualmente las props que le pasamos a `<StyledSpinner />` usemos la opción de JS de asignar valores por defecto a los parámetros recibidos en una función:

```js
const Spinner = () => {
  const { size = "medium", appearance = "blue", isTransparent = false } = props;

  return (
    // contenido
  )
}

```

De esta manera:
1. No hay que crear variables para guardar los valores por default.
2. Las props de `<Spinner />` nunca se van a evaluar como undefined
3. No hay que arreglar con ternarias las props que le pasamos a `<StyledSpinner />`

2023-02-08 17:30 UTC, wfercanas commented on src/components/feedback/Spinner/stories/Spinner.Colors.stories.js
> +Colors.argTypes = {
Esto se ve genial en el Storybook, aunque queda un poco aburridor estar repitiendo el mismo objeto en cada archivo.
Creo que podemos crear un archivo dentro de **stories/** que se llame **props.js** y ahí crear y exportar los objetos size, isTransparent, etc.

De esa forma, en cada archivo lo que hace es importar esos objetos e insertarlos en el objeto argTypes de la historia.

2023-02-08 21:28 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +const transparentOptions = [true, false];
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9b0d84a6ccd8d2bc79b3e8d132d0cec0b8f65ce1)

2023-02-08 21:29 UTC, M3rlin00 commented on src/components/feedback/Spinner/index.jsx
> +const defaultTransparent = "false";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/b5dea8b1c524720f76a5bc1750b0f965dd7792c0)

2023-02-08 21:29 UTC, M3rlin00 commented on src/components/feedback/Spinner/stories/Spinner.Colors.stories.js
> +Colors.argTypes = {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9ccc69c25eacf4e2a0cb3fb13067e4db5e2fa790)

2023-02-08 22:25 UTC, Andresbl123 commented
Se cumple con los criterios de aceptación

2023-02-09 14:49 UTC, wfercanas requested changes

2023-02-09 14:49 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +  size = sizes.includes(size) ? size : defaultSize;
Está bien la evaluación de la prop recibida. Sin embargo, aquí sobra la reasignación de size = size. Estaríamos reasignando sin necesidad el mismo valor (y esto va a a ocurrir la mayoría de las veces).

Podría refactorizar para que sólo exista reasignación de size cuando valga la pena. Lo mismo aplica para las demás props.

2023-02-10 19:55 UTC, wfercanas approved these changes

2023-02-10 19:55 UTC, merged