Label component
selsa-inube/design-system pull request #46
Opened 2023-02-08 19:42 UTC by Andresbl123

The Label component is implemented with its history including detailed documentation of its properties

2023-02-09 18:04 UTC, M3rlin00 commented on src/components/inputs/Label/stories/index.stories.jsx
> +  state: "",
le recomiendo settear un valor por defecto ya que si el objetivo de la historia es mostrar que pasa cuando no se hace pues si estaria bien pero si no, esto esta provocando la siguiente advertencia 
![image](https://user-images.githubusercontent.com/45011420/217898810-189b919b-ebb0-4b8e-b35e-5b67d2ba2761.png)

2023-02-09 18:04 UTC, M3rlin00 commented on src/components/inputs/Label/stories/index.stories.jsx
> +  ...label.args,
aqui no creo que sea necesario incluir el spread operator y los args nuevamente ya que de hecho en la linea 26 es donde los esta setteando

2023-02-09 18:04 UTC, M3rlin00 commented on src/components/inputs/Label/stories/index.stories.jsx
> +  title: "components/inputs/Label",
esta historia (excluyendo los otros comentarios ) ya estaria bien , sin embargo y de acuerdo con el figma son 3 las historias con los escenarios que se deberian de validar, la historia default, State, y All

2023-02-09 23:56 UTC, M3rlin00 commented on src/components/inputs/Label/stories/Label.stories.jsx
> +const stetes = ["default", "disabled", "focus", "invalid"];
creo que aqui se fue un errorla variable se deberia de llamar states

2023-02-09 23:56 UTC, M3rlin00 commented on src/components/inputs/Label/stories/Label.stories.jsx
> +const States = () => {
segun lo que fernando una vez me recomendo y me parece algo bueno para mejor legibilidad podria separar cada historia en un archivo diferente y no se si esto afecte pero creo que la extension para los archivos que son historias es js y no jsx

2023-02-09 23:56 UTC, M3rlin00 commented on src/components/inputs/Label/stories/Label.stories.jsx
> -  argTypes: {
el uso del los argTypes si estaba bien yo me referia era a que tenia algo como Default.args = { ...args } pero en cuanto a los argTypes si es una buena opcion dejarlo ya que le da una mejor operabilidad a estos controles , por que por ejemplo si yo no conozco cuales son los estados posibles pues puedo meter cualquier cosa ahi y no se como se va a comportar el componente
![image](https://user-images.githubusercontent.com/45011420/217965191-1aadd6cb-dac8-4fa2-a0ca-896108b257e7.png)

2023-02-11 00:37 UTC, M3rlin00 reviewed
cumple con los requerimientos

2023-02-14 16:14 UTC, wfercanas requested changes
Aparte de los comentarios dejados en el código, tenga en cuenta que hicimos varios ajustes importantes en el figma del componente. Cambiamos las props y las historias. Revise bien y ajuste en consecuencia.

2023-02-14 16:14 UTC, wfercanas commented on src/components/inputs/Label/stories/stories.args.js
> +const parameters = {
Este archivo lo estamos llamando props.js

2023-02-14 16:14 UTC, wfercanas commented on src/components/inputs/Label/stories/stories.styles.js
> +  border: 2px dashed #9747ff;
Este recuadro es una decoración de Figma, no es necesario replicarlo aquí.

2023-02-14 16:14 UTC, wfercanas commented on src/components/inputs/Label/styles.js
> +const stateColor = {
Extraiga todos los colores de los tokens de sistema. Estos los estamos actualizando ahora mismo, pronto estarán en main.

2023-02-15 17:52 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-02-15 20:44 UTC, wfercanas requested changes

2023-02-15 20:44 UTC, wfercanas commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +  title: "components/inputs/Default",
Publiquemos las historias empezando el title con "inputs/labels"

2023-02-15 20:44 UTC, wfercanas commented on src/components/inputs/Label/stories/props.js
> +        "Represent a label for an elemenent in a user interface. This can be associated with a control either by using the for attribute, or by placing the control inside the label element",
Por ahora nosotros no vamos a usar el anidamiento dentro del label, por lo que habría que quitar esa parte de esta descripción.

2023-02-15 20:44 UTC, wfercanas commented on src/components/inputs/Label/stories/stories.styles.js
> +/* const StyledContentAll = styled(StyledContentStates)`
No dejar este contenido comentado.

2023-02-15 20:44 UTC, wfercanas commented on src/components/inputs/Label/styles.js
> +      : stateColor[props.state] || sysTokensColor.default};
Aquí hay que separar 2 cosas:
1. La validación de que el valor que llegó por prop es correcto o no (para usar el valor por default), debería hacerlo `<Label />` no `<StyledLabel />`. La operación `||` aquí está cumpliendo esa función.
2. Aparte de los styled-components puede crear una función que retorne el token que debe usar el label. De esa manera a la propiedad color no le pasa una arrow function anónima sino una función nombrada. Esa función puede hacer los return que necesite sin anidar ternarias.

2023-02-17 00:25 UTC, Andresbl123 commented on src/components/inputs/Label/stories/props.js
> +        "Represent a label for an elemenent in a user interface. This can be associated with a control either by using the for attribute, or by placing the control inside the label element",
resuelto

2023-02-17 00:25 UTC, Andresbl123 commented on src/components/inputs/Label/stories/stories.styles.js
> +/* const StyledContentAll = styled(StyledContentStates)`
resuelto

2023-02-17 00:25 UTC, Andresbl123 commented on src/components/inputs/Label/styles.js
> +      : stateColor[props.state] || sysTokensColor.default};
resuelto

2023-02-17 16:28 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-02-17 16:28 UTC, cmarin001 commented on src/components/inputs/Label/index.jsx
> +const Label = (props) => {
hay que agregar la validacion de modo que cumpla con este item "Props that support a list of values, check that any value received is within such list."

2023-02-17 16:28 UTC, cmarin001 commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +  title: "components/inputs/Default",
falta el cambio en el que el title sea algo como "inputs/labels/Default"

2023-02-17 17:24 UTC, Andresbl123 commented on src/components/inputs/Label/index.jsx
> +const Label = (props) => {
ya ase había implementado, resuelto

2023-02-17 17:24 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +  title: "components/inputs/Default",
resuelto

2023-02-17 17:32 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-02-17 21:05 UTC, wfercanas requested changes

2023-02-17 21:05 UTC, wfercanas commented on src/components/inputs/Label/styles.js
> +const stateColor = {
No deberíamos tener textos en colores diferentes a los definidos en colors.sys.text

1. Para disabled usemos colors.sys.text.disabled (este token aún no existe, por lo que vamos a necesitar una actualización de los colores para poder resolver este punto).
2. Para invalid usemos sys.text.error

2023-02-17 21:05 UTC, wfercanas commented on src/components/inputs/Label/styles.js
> +const getColorByState = (isDisabled, isFocused, state) => {
Esta función se puede refactorizar para usar una sóla estructura de control. No sería con ternarias porque quedaría anidado, así que sería una secuencia de ifs en un orden que le garantice que el valor retornado es el correcto.

2023-02-17 21:05 UTC, wfercanas commented on src/components/inputs/Label/styles.js
> +const getColorByState = (isDisabled, isFocused, state) => {
Creo que el uso de los objetos sysTokensColor y stateColor sobra. Puede buscar aquí directamente el valor en colors cuando ingrese al cuerpo del if.

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/index.jsx
> +  const defaultState = states.includes(state) ? state : "default";
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +import Label from "../index";
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +  children: "Label (Help text)",
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.IsDefault.stories.js
> +Default.args = {
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.State.stories.js
> +  children: "Label (Help text)",
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.isDisabled.stories.js
> +  children: "Label (Help text)",
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/styles.js
> +const stateColor = {
resuelto

2023-02-20 21:49 UTC, Andresbl123 commented on src/components/inputs/Label/styles.js
> +const getColorByState = (isDisabled, isFocused, state) => {
resuelto

2023-02-21 19:27 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-02-21 22:34 UTC, wfercanas approved these changes

2023-02-21 22:41 UTC, merged