Cm/3904/switch
selsa-inube/design-system pull request #47
Opened 2023-02-09 17:48 UTC by M3rlin00

2023-02-10 15:32 UTC, Andresbl123 commented on src/components/inputs/Switch/stories/Switch.All.stories.js
> +export const All = AllTemplate.bind({});
El control de la props isDisabled no tiene ninguna funcionalidad por lo cual no se si sea como tal necesaria, para esta historia
![image](https://user-images.githubusercontent.com/74839801/218130280-72e52615-e8e7-45a1-b109-ff28989dd7da.png)

2023-02-10 15:32 UTC, Andresbl123 commented on src/components/inputs/Switch/stories/Switch.Default.stories.js
> +  console.log("Toggled:", state);
No se si estos console.log sean necesarios, de no ser así se podrían quitar

2023-02-10 16:26 UTC, M3rlin00 commented on src/components/inputs/Switch/stories/Switch.All.stories.js
> +export const All = AllTemplate.bind({});
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/7374a50a88b4b6ee4644fc78eacdb85f07065cd8)

2023-02-10 16:27 UTC, M3rlin00 commented on src/components/inputs/Switch/index.jsx
> +  size: PropTypes.string,
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/c4d348d12fc68213072e83771d26bc2a932c6db6)

2023-02-10 16:29 UTC, M3rlin00 commented on src/components/inputs/Switch/stories/Switch.Default.stories.js
> +  console.log("Toggled:", state);
en este punto pienso que es necesario ya que de otro modo como podemos saber que esta retornando el componente como output the manejo de esa funcion

2023-02-10 20:46 UTC, Andresbl123 commented
se cumple con los requerimientos

2023-02-10 21:39 UTC, wfercanas requested changes
No veo la necesidad de agregar un addon para el manejo de estados si el componente es stateless.
No ejecuté el `npm install`, por lo que no puedo ver aún la historia. Revise mis comentarios y si no está de acuerdo lo miramos. 

**Mi opinión es que este componente debe funcionar sin estado.**

2023-02-10 21:39 UTC, wfercanas commented on package.json
> +    "storybook-addon-pseudo-states": "^1.15.2",
¿Por qué instaló esta dependencia?

2023-02-10 21:39 UTC, wfercanas commented on package.json
> +    "@react-icons/all-files": "^4.1.0",
¿Por qué instaló esta dependencia?

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +  const [isToggled, setToggled] = useState(value);
Estos componentes son stateless, no es necesario que tengan un estado.

Recibe un `handleChange` y un `value` para que otro componente lo controle. Ese otro componente sí tiene y administra el estado. Pasa con esos checkbox y va a pasar también con los input o los select.

Quizá lo que sí faltó pasarle es la prop `checked`. Que es el atributo booleano que determina si el switch está prendido o apagado.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +        name={name}
Aquí faltaría la prop `checked` para poder controlar el componente.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +        onChange={handleToggle}
Aquí hay que usar la función `handleChange` que recibimos por props, precisamente para que el que sea que esté necesitando usar este switch decida qué hacer cuando cambia entre on y off.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +            style={{
Los estilos no los estamos pasando como objetos. Tampoco se los estamos aplicando directamente a los íconos. Habría que usar styled-components para esto y usar selectores de CSS para afectar a los íconos que estén anidados.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +        {isToggled ? (
Para evaluar si en input está prendido o apagado puede usar la pseudoclase `:checked` de CSS, no es necesario un estado de React.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +  const { id, isDisabled, name, value, handleChange, size } = props;
Aquí está permitiendo que size sea undefined si no le asigna el default value en caso de no recibir un size.

2023-02-10 21:39 UTC, wfercanas commented on src/components/inputs/Switch/stories/styles.js
> +import styled from "styled-components";
Renombremos este archivo como stories.styles.js

2023-02-10 21:41 UTC, wfercanas requested changes

2023-02-10 21:41 UTC, wfercanas commented on src/components/feedback/Spinner/index.jsx
> +import React from "react";
En esta PR no debería haber nada relacionado con los Spinner. Pilas.

2023-02-10 21:57 UTC, M3rlin00 commented on package.json
> +    "storybook-addon-pseudo-states": "^1.15.2",
esa fue la unica manera que encontre de lograr falsear por decirlo de algun modo los eventos de focus y hover desde storybook de manera que esa dependencia es necesaria para lograr lo que se pide desde figma que se vea en las historias de All y de States
![image](https://user-images.githubusercontent.com/45011420/218206478-035ba720-37ba-4dcb-a74e-af1b244215c5.png)

2023-02-11 05:00 UTC, cmarin001 commented on package.json
> +    "@react-icons/all-files": "^4.1.0",
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/3dfd385567340af35e96a0cbc4d6ad5398c10ac8)

2023-02-11 05:01 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +  const [isToggled, setToggled] = useState(value);
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/e581566aa7ed10f572555ef3dc939ce421601329)

2023-02-11 05:02 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +        name={name}
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/f178189f0090dac298095e264f46fe8c70955f43)

2023-02-11 05:02 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +        onChange={handleToggle}
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/a31d072bcf5dd7f4e0bf50136bf509608de6c779)

2023-02-11 05:02 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +            style={{
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/a31d072bcf5dd7f4e0bf50136bf509608de6c779)

2023-02-11 05:02 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +        {isToggled ? (
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/a31d072bcf5dd7f4e0bf50136bf509608de6c779)

2023-02-11 05:03 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +  const { id, isDisabled, name, value, handleChange, size } = props;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/f178189f0090dac298095e264f46fe8c70955f43)

2023-02-11 05:03 UTC, cmarin001 commented on src/components/inputs/Switch/stories/styles.js
> +import styled from "styled-components";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/ce206cc567fd13c43d502d9a1bdd471641cae996)

2023-02-11 05:04 UTC, cmarin001 commented on src/components/feedback/Spinner/index.jsx
> +import React from "react";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/9daf577a1f3d8114cb5c302a56126cb401df3858)

2023-02-14 00:24 UTC, wfercanas requested changes

2023-02-14 00:24 UTC, wfercanas commented on src/components/inputs/Switch/styles.js
> +  background: ${(props) =>
Dejemos las propiedades de css que manejan props al final de la lista de reglas y arriba las que son estáticas.
Facilita la lectura del código.

Además, dejemos un espacio cada que usemos el `&` con su respectiva anidación de propiedades.

2023-02-14 00:24 UTC, wfercanas commented on src/components/inputs/Switch/styles.js
> +      ? colors.ref.palette.neutral.n20
El contraste con el fondo blanco es muy escaso. Ya pasé a diseño que cambiemos este color disabled a n40.

2023-02-14 00:24 UTC, wfercanas commented on src/components/inputs/Switch/styles.js
> +        ? colors.ref.palette.neutral.n20
El contraste con el fondo blanco es muy escaso. Ya pasé a diseño que cambiemos este color disabled a g75

2023-02-14 00:24 UTC, wfercanas commented on src/components/inputs/Switch/styles.js
> +            bottom: 2.2px;
Cambie esta definición hecha manualmente por una calculada. El desplazamiento de la rueda debería ser:
`calc((spanHeight - circleHeight) / 2)`.

Es decir, para el small sería: `calc((16px - 12px) / 2)`

2023-02-14 00:24 UTC, wfercanas commented on src/components/inputs/Switch/styles.js
> +        ? colors.ref.palette.neutral.n20
Cambiemos este también a n40.

2023-02-15 22:04 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +    isDisabled,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/16ee6b12c1da1d3a882e5ee17046f20c45407bba)

2023-02-15 22:04 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +  &:focus {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/3e2dd0187e13b5f033825c1d2e87c502a343074a)

2023-02-15 22:05 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +  value: PropTypes.bool,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/3e2dd0187e13b5f033825c1d2e87c502a343074a)

2023-02-15 22:05 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +        checked={value}
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/7826310687d3046ffe8541aa9f44b4c248a1feb6)

2023-02-15 22:06 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +  cursor: pointer;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e0c5b0e8188bce46d662291a9406b7a336f8ebe2)

2023-02-15 22:06 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +  transition: 0.3s;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/807a4cecdb66f72089beb724ab03592130c89c21)

2023-02-15 22:06 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +  background: ${(props) =>
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/7a7db8852b0c68d3aef5d27156ecb804fa24f7bb)

2023-02-15 22:07 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +            bottom: 2.2px;
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/f80990f2242717b8cb52cb6fddbfab4df66052ce)

2023-02-15 22:08 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +      ? colors.ref.palette.neutral.n20
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/16ee6b12c1da1d3a882e5ee17046f20c45407bba)

2023-02-15 22:08 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +        ? colors.ref.palette.neutral.n20
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/16ee6b12c1da1d3a882e5ee17046f20c45407bba)

2023-02-15 22:08 UTC, cmarin001 commented on src/components/inputs/Switch/styles.js
> +        ? colors.ref.palette.neutral.n20
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/16ee6b12c1da1d3a882e5ee17046f20c45407bba)

2023-02-16 17:07 UTC, Andresbl123 commented on src/components/inputs/Switch/index.jsx
> +import PropTypes, { bool } from "prop-types";
esta variable de bool no se utiliza en ningun lodo, creo fuer algun erroe de importación

2023-02-16 17:30 UTC, Andresbl123 reviewed
no se si este creiterio "Triggered events are catched and printed in stories", haga referencia a la parte de action de storybook, de ser así faltaria esta parte 
![image](https://user-images.githubusercontent.com/74839801/219442534-64c20072-8685-4a9b-aa6e-9e6c53c0c5f2.png)
![image](https://user-images.githubusercontent.com/74839801/219442768-e83e9e73-7917-4857-b5a7-80a52514eeec.png)

2023-02-16 17:45 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +import PropTypes, { bool } from "prop-types";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/95158b36162cf4f177d7c5ace9c1186d4da56ddf)

2023-02-16 19:14 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +import PropTypes, { bool } from "prop-types";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/pull/47/commits/95158b36162cf4f177d7c5ace9c1186d4da56ddf)

2023-02-16 20:52 UTC, Andresbl123 commented
cumple con los requerimientos

2023-02-17 15:54 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +  const transformedSize = sizes.includes(size) ? size : defaultSize;
No me había dado cuenta que cuando uno usa el oneOf en los prop-types, si no llega un valor de la lista él le coloca un error y le enuncia los valores que se aceptan 😅 .

Siendo ese el caso, los console.warn sobrarían.

2023-02-17 16:53 UTC, wfercanas requested changes

2023-02-17 16:53 UTC, wfercanas commented on src/components/inputs/Switch/index.jsx
> +import { MdDone, MdClose } from "react-icons/md/index";
El `/index` sobra, ya que se busca por default el archivo index.

2023-02-17 16:53 UTC, wfercanas commented on src/components/inputs/Switch/stories/Switch.Default.stories.js
> +const SwitchComponent = ({
Bien, la necesidad de crear a SwitchComponent significa que efectivamente Switch es un componente controlado. 

* En el caso de un input tipo 'text' normal, que éste sea controlado significa que su value lo determina un componente controlador, lo mismo que los cambios al valor (onChange).
* En el caso de un input 'checkbox', controlado significa controlar el checked y el cambio del checked entre true y false.

**Conclusión:**
Como vamos a necesitar ese componente controlador en todos los componentes que sean inputs para poder mostrar las historias funcionando, lo mejor es crear sólo 1 vez ese componente y reutilizarlo en las diferentes historias. Así que:
* Creemos un archivo dentro de stories/ un archivo llamado SwitchController.jsx
* Ahí creemos el componente SwitchController.
* SwitchController crea el state y define el handleChange para modificar ese state.
* SwitchController retorna un `<Switch />`
* SwitchController recibe props y se las pasa sin modificación al switch en el return: `<Switch {...props} />`
* Se importa este único SwitchController en las diferentes historias y se usan las args para jugar con las propiedades del Switch

2023-02-17 20:32 UTC, cmarin001 commented on .storybook/main.js
> +    "storybook-addon-pseudo-states",
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/402ca79d983f846c5ceafb50319dbef1d1d2bc07)

2023-02-17 20:32 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +  if (!sizes.includes(size)) {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/5fb8c1d9cf4721a7303c32a18d3a517d81370b7a)

2023-02-17 20:33 UTC, cmarin001 commented on src/components/inputs/Switch/index.jsx
> +import { MdDone, MdClose } from "react-icons/md/index";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ba1d2e097f1184fb32d459882915b9130154ee49)

2023-02-17 20:33 UTC, cmarin001 commented on src/components/inputs/Switch/stories/Switch.Default.stories.js
> +const SwitchComponent = ({
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/2ce08b9436802d869831c5546f22863558ce5024)

2023-02-17 21:33 UTC, Andresbl123 commented
cumple con lo requerimientos

2023-02-20 23:32 UTC, wfercanas approved these changes

2023-02-20 23:37 UTC, merged