Cm/4025/stack
selsa-inube/design-system pull request #49
Opened 2023-02-13 22:32 UTC by cmarin001

2023-02-14 21:12 UTC, cmarin001 commented on src/components/layouts/Stack/index.jsx
> +const defaultAligmentContent = "flex-start";
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/353fc8dab43e359c972082f8bedf3d3adc514d3c)

2023-02-14 21:14 UTC, cmarin001 commented on src/components/layouts/Stack/index.jsx
> +    wrap,
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/64c91243e604098953e55f0c14d740f0196ac22a)
documentacion acerca del uso de propiedades booleanas en styledComponents
https://styled-components.com/docs/api#transient-props
approach utilizado para resolver incidencia
https://maximeblanc.fr/blog/how-to-fix-the-received-true-for-a-non-boolean-attribute-error/

2023-02-15 14:54 UTC, Andresbl123 commented
Cumple con los criterios de aceptación y la implementación de las historias

2023-02-15 16:51 UTC, wfercanas requested changes

2023-02-15 16:51 UTC, wfercanas commented on src/components/layouts/Stack/index.jsx
> +      wrap={+wrap}
¿Por qué `+wrap`?

2023-02-15 16:51 UTC, wfercanas commented on src/components/layouts/Stack/stories/props.js
> +  options: [
Como esto va a quedar en la documentación (Docs), no dejemos estos valores. Lo mismo pasa abajo con `gap`, que pareciera que tuviera una lista específica de gaps.

Dejemos estas propiedades sin "Select" y más bien en las args de la historia pase la lista de rectángulos y el gap como un string cualquiera.

2023-02-15 22:14 UTC, cmarin001 commented on src/components/layouts/Stack/index.jsx
> +      wrap={+wrap}
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/64c91243e604098953e55f0c14d740f0196ac22a)
como se menciona en este apartado fue la manera que encontre para solucionar el lio que se produce al pasar booleans properties a los styled components
documentacion acerca del uso de propiedades booleanas en styledComponents
https://styled-components.com/docs/api#transient-props
approach utilizado para resolver incidencia
https://maximeblanc.fr/blog/how-to-fix-the-received-true-for-a-non-boolean-attribute-error/

2023-02-16 02:51 UTC, cmarin001 commented on src/components/layouts/Stack/stories/props.js
> +  options: [
**incidencia resuelta**
[commitResolver](https://github.com/selsa-inube/design-system/commit/f591804546667ef178006817aee683388942cfd7)

2023-02-16 15:18 UTC, Andresbl123 reviewed
se debe ajustar el requerimiento de console.warn

2023-02-16 17:38 UTC, Andresbl123 commented
cumple con los requerimientos

2023-02-16 17:48 UTC, Andresbl123 commented
se cumple con los requerimientos y criterios

2023-02-17 20:24 UTC, wfercanas requested changes

2023-02-17 20:24 UTC, wfercanas commented on src/components/layouts/Stack/index.jsx
> +      wrap={+wrap}
El problema no es sólo por ser boolean, sino porque hay algunos elementos de HTML que tienen ciertos atributos HTML que se pueden llamar igual que las props. Por ejemplo, los input tienen un atributo required, que usado se ve `<input type="text" required />`. Lo mismo ocurre con `disabled`.

Entonces, cuando a un styled-component le colocamos una prop cualquiera como `propName = {true}`, lo que va a intentar hacer la librería es ver si ese atributo existe, validar si es de tipo boolean y activar ese atributo en el elemento HTML.

Todo funciona bien cuando esto se hace con una prop que se llame igual que un atributo HTML y que funcione de forma booleana. Por ejemplo: `<StyledInput type="text" required={true} disabled={false} />`. Al hacer que la prop trascienda (transcient props), va a encontrar que esos atributos HTML existen y son booleanos, entonces no pasa nada grave y al final en el DOM el elemento queda como `<input type="text" required disabled />`

Pero, si hacemos `<StyledInput wrap={true} />`, nos vamos a encontrar con que el atributo wrap sí existe en HTML pero que no es un atributo booleano, entonces en consola va a decir con un error: **Warning: Received `true` for a non-boolean attribute `wrap`.**. Cosa que es cierta, pues en la API del atributo wrap indica que no es boolean.

**Conclusión**:
1. Para este caso específico, cambiemos la prop wrap para que no sea boolean, sino que sea oneOf(["wrap", "nowrap"])  y que por default sea "nowrap". Es preferible hacer este cambio que jugar con los tipos y los valores falsy para que funcione.
2. En situaciones como los input o los botones, al StyledInput o StyledButton habría que pasarle la prop disabled={isDisabled} para que ahí sí aplique lo que se espera en el DOM.

2023-02-17 20:24 UTC, wfercanas commented on src/components/layouts/Stack/index.jsx
> +    : defaultJustifyContent;
Por el cambio hecho a `wrap`, habría que agregar esa prop en estas validaciones.

2023-02-17 20:56 UTC, cmarin001 commented on src/components/layouts/Stack/index.jsx
> +  if (!flexAligments.includes(alignItems)) {
**incidencia resuelta**
[commitResolver](https://github.com/selsa-inube/design-system/commit/a9e26538a250658de08ce118ba483d0ea987d490)

2023-02-17 20:56 UTC, cmarin001 commented on src/components/layouts/Stack/index.jsx
> +    : defaultJustifyContent;
**incidencia resuelta**
[commitResolver](https://github.com/selsa-inube/design-system/commit/9a33ad011a74bc8bd61d4baa5968fbf685aff34d)

2023-02-17 21:54 UTC, Andresbl123 commented
cumple con los requerimientos

2023-02-20 23:50 UTC, wfercanas requested changes

2023-02-20 23:50 UTC, wfercanas commented on src/components/layouts/Stack/index.jsx
> +export const directionAligments = ["row", "column"];
En varios lugares tiene "Aligments" y es "Alignments"

2023-02-21 00:43 UTC, wfercanas approved these changes

2023-02-21 00:45 UTC, merged