Ab/4028/Text
selsa-inube/design-system pull request #51
Opened 2023-02-16 16:50 UTC by Andresbl123

Feature componente de Text,  que permite el uso de tokens tipográficos desacoplados de etiquetas de texto HTML como h1, h2, ..., p, span, legend, figcaption, blockquote",

2023-02-16 19:28 UTC, cmarin001 reviewed
la historia esta bien sin embargo considero que deberiamos seguir un estandar a la hora de nombrar los directorios y los archivos mismos, por tal razon  considero que aqui
![image](https://user-images.githubusercontent.com/45011420/219467438-974d79fd-252a-4395-99dc-ab5ea4e338a7.png)
deberia quedar( **src/components/data** ) en minuscula como los demas directorios

2023-02-16 20:14 UTC, cmarin001 commented on src/components/Data/index.jsx
> +const elementsHtml = [
falta agregar las validaciones que logren cumplir con este criterio (The props received are validated against the authorized values so the component can use them.)

2023-02-16 21:59 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const elementsHtml = [
resuelto, con respecto al cambio del nombre del directorio "Data", ya que el vsc no me deje

2023-02-16 22:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const appearances = [
resuelto

2023-02-17 15:53 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-02-21 00:40 UTC, wfercanas requested changes

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +const appearances = [
Extraigamos esta información del objeto que tiene los tokens de sistema para colors. Ahora que incluimos el color disabled ya este array quedó desactualizado.

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +const typos = [
Extraigamos esta información de los tokens de typography. Si hay un cambio allá, aquí ya queda actualizado.

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +import React from "react";
Persiste el error de crear la carpeta Data con mayúscula.

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +  const transformedalign = aligns.includes(align) ? align : defaultalign;
Usar camelCase

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +const defaultElementsHtml = "p";
Se leería mejor `defaultHtmlElement`

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +const elementsHtml = [
Se lee mejor `htmlElements`

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/stories/Text.Paragraphs.stories.js
> +import Text from "../index";
Si inspecciona el DOM en Storybook, va a ver que hay algunos párrafos sin contenido. Revise.

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/stories/Text.Paragraphs.stories.js
> +const Paragraphs = ({ ...args }) => {
Aquí dice que le va a pasar unas args, pero al final no las pasa. En los controls de la historia todos los campos estan `Choose an option`

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/stories/props.js
> +  options: ["start", "center", "end", "justify"],
Este array ya fue definido en index.jsx. Exportelo allá e importelo aquí, así sólo hay una fuente de la verdad. Lo mismo pasa para los demás array de `as`, `appearance`, ...

2023-02-21 00:40 UTC, wfercanas commented on src/components/Data/index.jsx
> +const Text = (props) => {
Al jugar con las historias, veo que se aplican los padding y margin que tiene por defecto el navegador. Agreguemos props para padding y margin, que reciban un string y que por default ambas sean "0px".

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const typos = [
Resuelto

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +import React from "react";
Resuelto

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const appearances = [
Resuelto

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +  const transformedalign = aligns.includes(align) ? align : defaultalign;
Resuelto

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const defaultElementsHtml = "p";
Resuelto

2023-02-21 23:02 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const elementsHtml = [
Resuelto

2023-02-21 23:03 UTC, Andresbl123 commented on src/components/Data/stories/Text.Paragraphs.stories.js
> +import Text from "../index";
Resuelto

2023-02-21 23:03 UTC, Andresbl123 commented on src/components/Data/stories/Text.Paragraphs.stories.js
> +const Paragraphs = ({ ...args }) => {
resuelto

2023-02-21 23:03 UTC, Andresbl123 commented on src/components/Data/stories/props.js
> +  options: ["start", "center", "end", "justify"],
Resuelto

2023-02-21 23:03 UTC, Andresbl123 commented on src/components/Data/index.jsx
> +const Text = (props) => {
Resuelto

2023-02-24 14:29 UTC, cmarin001 commented
cumple con los requerimientos

2023-02-27 17:27 UTC, wfercanas requested changes

2023-02-27 17:27 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +    align = "start",
Arriba ya están definidas las variables default, es mejor usar esas aquí y no colocar el string directo. De lo contrario habría 2 fuentes de la verdad.

2023-02-27 17:27 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +import { StylesText } from "./styles";
Cambiar styled-component por `StyledText`

2023-02-27 17:27 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +const transformPropValue = (value, allowedValues, defaultValue) => {
Crear una función como esta podría llegar a implicar que más bien creemos una función que puedan utilizar todos los componentes para chequear sus props (podríamos hacerle tests y toda la cosa). Sin embargo, creo que no hace falta. Explicación:

1. Es una función que debe cumplir 2 tareas: validar que el valor de una prop está incluido en una lista de opciones válidas y retornar ya sea el valor validado o un defaultValue.
2. La función tendría que adquirir el conocimiento sobre el defaultValue en el llamado de la función, por lo que al final la función devolverá lo que le digan que es el defaultValue (lo que no garantiza que sea el valor correcto, porque el llamado de la función puede hacerse mal).
3. Si hacemos que no, que el conocimiento del defaultValue lo conserve solamente el componente al que le interesa, nos quedaríamos sólo con la responsabilidad de validar si la prop está en la lista de valores correctos.
4. Esa sola responsabilidad ya la tiene el método .includes(), por lo que no tendría sentido crear una nueva función para hacer lo mismo.

**Conclusión**: mantengamos el uso de ternarias para la evaluación de una prop con respecto a una lista de opciones. Usamos un método estándar de los array como es includes y no propagamos el conocimiento del defaultValue a otros contextos.

2023-02-28 17:14 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +const regex = /^[0-9]+px(\s+[0-9]+px){0,3}$/;
Resuelto

2023-02-28 17:16 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +const alignsOptios = ["start", "center", "end", "justify"];
Resuelto

2023-02-28 17:16 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +const appearencesOptions = Object.entries(colors.sys.text).map(([key]) => {
Resuelto

2023-02-28 17:16 UTC, Andresbl123 commented on src/components/data/Text/index.jsx
> +    align = "start",
Resuelto

2023-03-01 16:35 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-03-01 22:31 UTC, wfercanas requested changes

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +});
Aqui pasa igual que en el caso anterior.

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/stories/Text.Titles.stories.js
> +        <Text
Dejemos este `<Text />` con los valores por defecto, así las propiedades no se ven gigantes o muy pequeñas si cambian los controls en storybook.

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  align: PropsType.oneOf(alignsOptions).isRequired,
Si align tiene valor por defecto, no deberíamos dejarle el `isRequired`.

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  as: PropsType.oneOf(htmlElements).isRequired,
Si `as` tiene valor por defecto, no deberíamos dejarle el `isRequired`

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  typo: PropsType.oneOf(typosOptions).isRequired,
Si `typo` tiene valor por defecto, no deberíamos dejarle `isRequired`

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  "span",
Si alguien llega a necesitar un `span`, le va a aparecer como `display: block`.

No agreguemos por ahora una prop para el display, pero sí en los estilos de `StyledText` agreguemos una función para la propiedad display. Si la prop `as` es span, usemos `inline`, si no usemos `block`

2023-03-01 22:31 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +    return result;
Este `return` es reduntante con el de abajo. Puede dejar sólo el de abajo.

2023-03-02 16:32 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-03-06 14:54 UTC, wfercanas commented on src/components/data/Text/index.jsx
> +  "span",
Bueno, ahí quedó bien pero creo que no supe explicarme. Podemos dejar la arrow function de la propiedad css: display: `${({as}) => as === "span" ? "inline" : "block" }`

2023-03-06 14:59 UTC, wfercanas commented on src/components/data/Text/stories/Text.Titles.stories.js
> +        <Text
Aquí los textos que describen las propiedades tipográficas css del título siguen variando con el título. Usemos sólo las por defecto para que no cambien.

2023-03-07 23:24 UTC, wfercanas approved these changes

2023-03-07 23:25 UTC, merged