remove variable darkWhenFilled in `<Button />`
selsa-inube/design-system pull request #520
Opened 2023-09-18 21:44 UTC by Andresbl123

the `darkWhenFilled` variable is removed, and the scope of the `appearanceChildrens` function is changed

2023-09-19 19:50 UTC, cmarin001 reviewed
falta probar que en todos los lugares donde se usa <button/> funcione

2023-09-19 19:50 UTC, cmarin001 commented on src/components/inputs/Button/index.tsx
> +  const { children, type = "button", path } = props;
la tarjeta dice 'only destructure type and path props in Button' y aqui tenemos children

2023-09-19 21:42 UTC, Andresbl123 commented on src/components/inputs/Button/index.tsx
> +  const { children, type = "button", path } = props;
Resuelto

2023-09-19 22:47 UTC, cmarin001 reviewed
tenemos errores 
![image](https://github.com/selsa-inube/design-system/assets/45011420/b5a73349-c823-48ae-be43-3d0bc9077010)

2023-09-20 21:43 UTC, wfercanas requested changes

2023-09-20 21:43 UTC, wfercanas commented on src/components/inputs/Button/index.tsx
> +function appearanceChildrens(variant: Variant, appearance: Appearance) {
Renombrar la función como `childrenAppearence`. Children ya es en sí mismo un plural, por eso no va con 's' al final.

2023-09-21 20:41 UTC, wfercanas approved these changes

2023-09-23 16:06 UTC, wfercanas approved these changes

2023-09-23 16:06 UTC, merged