`<Button />:` add `cursorHover` and `parentHover` props
selsa-inube/design-system pull request #521
Opened 2023-09-19 21:21 UTC by cmarin001

To provide greater flexibility and interactivity, this PR introduces two new optional props to the `<Button />` component: `cursorHover` and `parentHover`.

2023-09-20 15:10 UTC, Andresbl123 approved these changes
Cumple requerimiento

2023-09-20 21:33 UTC, wfercanas requested changes

2023-09-20 21:33 UTC, wfercanas commented on src/components/inputs/Button/styles.ts
>        return "progress";
Cuando no está disabled, está mostrando el cursor como si estuviera cargando. Ya luego si uno le pone `loading = true` aparece cargando pero porque está así en general.

En general debería tener por defecto el `cursor: pointer`

2023-09-20 21:33 UTC, wfercanas commented on src/components/inputs/Button/index.tsx
Falta asignar los valores por defecto de ambas props. Ambas en `false`.

2023-09-25 16:07 UTC, Andresbl123 commented on src/components/inputs/Button/styles.ts
>        return "progress";
resuelto

2023-09-25 16:07 UTC, Andresbl123 commented on src/components/inputs/Button/index.tsx
Resuelto

2023-09-25 21:51 UTC, wfercanas commented on src/components/inputs/Button/styles.ts
>        return "progress";
Resuelto el que no aparezca en progress, pero no aparece en pointer por defecto. Eso porque como hay un if con `|| variant="filled"`, pues eso da true y retorna es default.

No importa la variante, un botón siempre va pointer si no está disabled ni loading.

2023-09-26 21:22 UTC, wfercanas approved these changes

2023-09-26 21:22 UTC, merged