Replace `StyledSpan` for a `<Stack/>` in `<Button />`
selsa-inube/design-system pull request #522
Opened 2023-09-20 15:43 UTC by Andresbl123

replace `StyledSpan` by `<Stack />`, avoiding creating unnecessary **styled-components,** this also avoids having to run code that should not be

2023-09-20 21:15 UTC, wfercanas requested changes

2023-09-20 21:15 UTC, wfercanas commented on src/components/inputs/Button/index.tsx
> +        <Stack>
Falta que el Stack centre el contenido: `align-items`

2023-09-20 21:27 UTC, Andresbl123 commented on src/components/inputs/Button/index.tsx
> +        <Stack>
resuelto

2023-09-21 20:35 UTC, wfercanas approved these changes

2023-09-21 20:35 UTC, merged