Make it a wrapper that just render children in `<OptionList />`
selsa-inube/design-system pull request #529
Opened 2023-09-27 01:21 UTC by Andresbl123

Let’s prevent a props drilling problem that may cause that the <Select /> component as a whole becomes harder to maintain.
Make `<OptionList />` a component that is only useful as a styled container that **renders children** and that’s it.
The styles are defined so that it appears or disappear when necessary and looks nice behind to the select input and nothing more.

2023-09-28 21:07 UTC, wfercanas requested changes

2023-09-28 21:07 UTC, wfercanas commented on src/components/inputs/Select/index.tsx
> +    if (e) {
No necesita validar el evento, ese parámetro debe venir siempre que esta función esté amarrada a un evento click.

2023-09-28 21:07 UTC, wfercanas commented on src/components/inputs/Select/index.tsx
> +  );
No deberíamos tener este estado. El controlador debe manejar el estado del value y pasarnos por prop el value.
Adicional al value, el controlador nos debería pasar un onChange y por ahí es que nosotros dentro del select le pasamos un nuevo value cuando exista un click sobre una option.
Ese onChange actualiza el value en el padre, quien a su vez modifica la prop value que nos llega y por ende renderizamos de nuevo usando el nuevo value.

2023-09-28 21:07 UTC, wfercanas commented on src/components/inputs/Select/index.tsx
> +      setSelectedOption(e.target.textContent);
Aquí ejecutaríamos onChange, no este setter de un estado local.

2023-09-29 14:19 UTC, Andresbl123 commented on src/components/inputs/Select/OptionList/index.tsx
> +    if (onClick) onClick(e);
Resuelto

2023-09-29 14:19 UTC, Andresbl123 commented on src/components/inputs/Select/OptionList/index.tsx
> +      onClick={(e: React.ChangeEvent<HTMLInputElement>) => handleOptionClick(e)}
Resuelto

2023-09-29 14:20 UTC, Andresbl123 commented on src/components/inputs/Select/index.tsx
> +    if (e) {
Resuelto

2023-09-29 15:41 UTC, Andresbl123 commented on src/components/inputs/Select/index.tsx
> +    if (e) {
Resuelto

2023-09-29 15:41 UTC, Andresbl123 commented on src/components/inputs/Select/index.tsx
> +  );
Resuelto

2023-09-29 15:45 UTC, Andresbl123 commented on src/components/inputs/Select/index.tsx
> +      setSelectedOption(e.target.textContent);
Resuelto

2023-09-29 16:59 UTC, wfercanas requested changes

2023-09-29 16:59 UTC, wfercanas commented on src/components/inputs/Select/index.tsx
Creo que la prop `value` no debería ser opcional. Debe llegar un value ahí sea `""` porque de esa manera desde un principio tenemos la conexión entre el padre y el select . Sería un componente controlado.

2023-09-29 17:30 UTC, Andresbl123 commented on src/components/inputs/Select/index.tsx
Resuelto

2023-10-02 14:57 UTC, wfercanas approved these changes

2023-10-02 14:57 UTC, merged