Cm/4097/button
selsa-inube/design-system pull request #54
Opened 2023-02-21 22:19 UTC by cmarin001

2023-02-22 16:45 UTC, Andresbl123 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +Disabled.argTypes = {
falta la descriptions de la props de children segun figma

2023-02-22 16:52 UTC, Andresbl123 commented on src/components/inputs/Button/index.jsx
> +          appearance={
No se si sea conveniente que la deción del color la tenga que realizar el componente, creo que sería más optimo implementar una función y que esta sea la encarda de realizar esta decisión

2023-02-22 16:52 UTC, Andresbl123 commented on src/components/inputs/Button/stories/Button.Default.stories.js
> +Default.args = {
no se si sean necesario los valores de los args, ya que la historia debería mostrat el componente con los valores por defecto cuando no se le pasan las props

2023-02-22 16:52 UTC, Andresbl123 commented on src/components/inputs/Button/stories/props.js
> +const variant = {
variant según figma no tiene descriptions

2023-02-22 17:43 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Default.stories.js
> +Default.args = {
en este caso considero que si es necesario pasarle las props, ya que en efecto el componente toma los valores por defecto, sin embargo, cuando no se pasan las props saltan la serie de advertencias 
![image](https://user-images.githubusercontent.com/45011420/220711394-377ccfcd-9163-4511-9ad3-cd01529f2bc2.png)
de modo que si uno puede no pasarle las props y ver como solo carga los valores por defecto pero seria mas a mi modo de ver una prueba que algo para una historia como tal

2023-02-22 17:45 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +Disabled.argTypes = {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/52c984ca358bd36d7dc4aa52dee0744ae125c0f3)

2023-02-22 17:45 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +          appearance={
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/c5a6b8c8b59c284d79dd58b8a401b19c52157d2d)

2023-02-22 17:46 UTC, cmarin001 commented on src/components/inputs/Button/stories/props.js
> +const variant = {
incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/6565665e6e49f4670ecc1aea798691a0deff3df2)

2023-02-23 02:41 UTC, Andresbl123 commented
cumple con los requerimientos

2023-02-23 22:58 UTC, wfercanas requested changes

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +  const spinnerColor = isDisabled
Es preferible que esto no sea una variable sino una función. Asi por dentro del cuerpo de la función puede hacer las evaluaciones con el uso de ifs y hacer return según vaya siendo el caso.
Más adelante entonces no pasa `spinnerColor` sino `spinnerColor()`. De hecho siendo función podría dejarlo como `getSpinnerColor()`

Con lo anterior evitamos anidar ternarias.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +    ? colorHomologationSpinner[appearance]
Aquí está usando el appearance que pasó el usuario, que puede no ser un appearance correcto dentro de la lista de opciones.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +        appearances.includes(appearance) ? appearance : defaultAppearance
Aquí está controlando el uso de un appearance válido ya dentro de la asignación de la prop del styled-component.
Esto tiene 3 temas a revisar:
1. La lógica que venga antes de este return puede estar usando un valor en estas variables que no es correcto y que no se va a alinear con lo que finalmente le llegue al styled-component.
2. Hace que la lectura del return sea más compleja porque hay más lógica mezclada con jsx.
3. Cambia con respecto a como lo venimos haciendo en los otros componentes que ya pasamos a `main`. Hay que dejar un estándar. Si es este, hay que justificar por qué y si sí, yo tendría que crear las tareas para editar los otros componentes.

Revise y si ve que se justifica cambiar la forma en que venimos desarrollando los componentes, me escribe.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +          size={spacing === "wide" ? "medium" : "small"}
Esta línea no está funcionando. Si cambio de "wide" a "compact" sigue apareciendo el Spinner "medium". Además, para todos los botones se está usando el Spinner small en los mockups (height y width de 24px).

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +          appearance={spinnerColor}
Cuando el botón es secondary, el spinner es color oscuro, no blanco. Lo mismo pasa con el botón que es warning.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +  width: 100%;
Si escribo un texto para el botón como "Click aquí para ingresar". El botón se queda de un ancho específico y el texto se pierde con el salto de línea. Hagamos que:
1. El botón se vaya estirando a medida que se alarga el contenido.
2. El botón se estire si además del texto largo le agregamos un iconAfter o un iconBefore (o ambos).

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  appearance: "primary",
Aunque a esta historia le está pasando "primary" se está pintando como "secondary"

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  // iconAfter: "+",
No dejar código comentado.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  isLoading: false,
Aunque aquí le está pasando `isLoading: false`, en la historia está quedando `true`.

2023-02-23 22:58 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +            {children}
La fuente del texto está quedando **Arial**, no se está usando el labelLarge de los mockups.

2023-02-23 23:59 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  appearance: "primary",
Osea si, pero es como lo indica el mockup
![image](https://user-images.githubusercontent.com/45011420/221058414-7068c694-a80b-465c-a2c5-d0a230b10587.png)
y toma ese color asi por que se supone que esta disabled que corresponde con el n30

2023-02-24 00:02 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  isLoading: false,
aqui en la historia esta quedando false
![image](https://user-images.githubusercontent.com/45011420/221058854-ec5cf5f2-1a7c-4f8b-96f0-f09c03095dca.png)
ya que si fuese true quedaria de la siguiente manera
![image](https://user-images.githubusercontent.com/45011420/221058934-d92740e1-5763-47c9-a422-3a0c4ce0c3ec.png)

2023-02-24 00:07 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +  // iconAfter: "+",
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/1af85123d5250bc5d07dc88f27c5a7a1fe5b4bfb)

2023-02-24 22:04 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +  const spinnerColor = isDisabled
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/cdb20255470a5b992f61f99c74d4a2e35781dc60)

2023-02-24 22:04 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +    ? colorHomologationSpinner[appearance]
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/cdb20255470a5b992f61f99c74d4a2e35781dc60)

2023-02-24 22:04 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +        appearances.includes(appearance) ? appearance : defaultAppearance
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/cdb20255470a5b992f61f99c74d4a2e35781dc60)

2023-02-24 22:04 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +          size={spacing === "wide" ? "medium" : "small"}
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/cdb20255470a5b992f61f99c74d4a2e35781dc60)

2023-02-24 22:18 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +  width: 100%;
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/0d2913666ff1afb3a64a2c1c8cfc259fcb4cfd1b)

2023-02-25 00:12 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +          appearance={spinnerColor}
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/1275acfa4e53f4a3b2ff3a4319463d980d35b30a)

2023-02-25 00:29 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +            {children}
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ba5d5f942de68b7a6fb41d95a337524de9e54c21)

2023-02-27 16:05 UTC, Andresbl123 commented
cumple con los requerimientos

2023-02-27 17:39 UTC, wfercanas commented on src/components/inputs/Button/index.jsx
> +  const spinnerColor = isDisabled
Veo que ya está la función y que dentro estamos usando algunos ifs, pero dentro de ellos estamos anidando ternarias. El cambio tiene la intención de evitar ese anidamiento de ternarias y si es el caso anidar ifs:
```js
if (variant !== filled) {
  if (appearance === "secondary") {
    return "dark";
  }
}

```

2023-02-28 02:34 UTC, wfercanas requested changes

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +      && > div {
Con un sólo `&` es suficiente.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +      && > div {
Este selector afecta si hay un <div> hijo del button, que creo que el único caso posible es cuando está el spinner. Si es así, estas propiedades sobrarían porque no están pensadas para organizar un spinner sino un texto.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +        white-space: nowrap;
Esta propiedad hace que el texto se pueda desbordar el `div`, ¿por qué se agrega aquí?

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +        text-overflow: ellipsis;
En los diseños de figma no está contemplado el caso donde un botón deba resumir el texto con una elipsis.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +        span {
Este span está anidado dentro del selector de `& > div`, ¿cuál es la intención? Sigo pensando que ese div sólo aparece con los spinner, luego sería un span dentro del spinner.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +  ${(props) =>
A partir de este punto estamos anidando evaluaciones de props para definir propiedades como el color, background-color, border. Evitemos ese anidamiento, que cada propiedad tenga su fila única y que el resultado sea hallado sin este anidamiento. 

Si le delegamos la responsabilidad del color a una función sería algo como:
```js
background-color: ${(props) => getBackgroundColor(props)}
```

Si lo que hacemos es un objeto que hace la homologación, sería algo como:
```js
background-color: ${(props) => backgroundColor[appearance]}
```

**Creo que valdría la pena:**
1. Crear un objeto de homologación para el caso en que no es disabled (appearanceColors).
2. Crear otro objeto de homologación cuando sí es disabled (disabledColors).
3. Crear otro objeto de homologación para los hover (hoverColors) --> **Este de hecho ya está hecho**.
4. Crear una función que evalúa ciertas props para saber qué objeto usar.
5. Esa función retorna el token de sistema que encuentre en el objeto de homologación que corresponda.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +      border: none;
Creo que conviene separar las propiedades del border, usar `border-color`, `border-style` y `border-width`, de esa manera no estamos reemplazando estilos en la cascada sino que cada cosa se defina una vez y en un lugar donde se evalúan las props para saber qué estilo se debe aplicar.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +          background-color: transparent;
Aquí volvemos a tocar el backgroundColor, color y border, apelando a la cascada para que al final quede aplicado el estilo correcto. Mejor definamos como se indica antes un lugar donde controlemos al final cuál valor debería quedar en la propiedad sin contar con la cascada para eso.

2023-02-28 02:34 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +      pointer-events: none;
En la especificación no está que se eliminen los eventos de puntero sobre los botones en loading.
Sí se pide que si el botón está disabled, se use `cursor: not-allowed` para ayudar a decirle al usuario que no puede usar el botón. Para el loading podría usarse el `cursor: progress` si es el caso.

2023-02-28 23:07 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +const colorHomologationSpinner = {
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/2cb6191f97c0a24d9900550c13b36158b7e6caf0)

2023-02-28 23:07 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +  const homologationSpinnerColor = colorHomologationSpinner.secondary;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/2cb6191f97c0a24d9900550c13b36158b7e6caf0)

2023-02-28 23:07 UTC, cmarin001 commented on src/components/inputs/Button/index.jsx
> +  iconAfter: PropTypes.node,
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/d60b0a4c3ffda1593604e53701f77ac39d10af8a)

2023-02-28 23:08 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Appearances.stories.js
> +  iconBefore: "+",
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/773870d6a27874893824f8c7954b8177ef0aa222)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Icons.stories.js
> +            iconAfter={item === 1 ? "+" : null}
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/773870d6a27874893824f8c7954b8177ef0aa222)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      && > div {
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +        white-space: nowrap;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +        text-overflow: ellipsis;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +        span {
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +  ${(props) =>
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      border: none;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:09 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +          background-color: transparent;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-02-28 23:10 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      pointer-events: none;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/bc942a88d3a367a864f9c3bf6f514a1805c290aa)

2023-03-01 13:15 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Disabled.stories.js
> +import React from "react";
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/f5df27630e1b253cf72e258e0624d084459274d6)

2023-03-01 15:27 UTC, Andresbl123 commented on src/components/inputs/Button/stories/Button.Default.stories.js
> +Default.args = {
creo que al hacer este cambio, en la historia Default, se podrían quitar las propiedad de Default.args, de las props que ya tienen un valor por defecto, con esto la historia nos muestra como se ve el componente al no pasar estas props que tienen un valor por defecto

2023-03-01 16:16 UTC, cmarin001 commented on src/components/inputs/Button/stories/Button.Default.stories.js
> +Default.args = {
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/eebb51583a0073f01bb005588c71d573976945cb)

2023-03-01 19:10 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-02 04:36 UTC, wfercanas requested changes

2023-03-02 04:36 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +);
Creo que armar estos objetos llenos de `transparents` o llenos de `n0` hace que el código sea más complejo de leer, no solo por estas líneas con el `Object.fromEntries` y los nombres de estos objetos, sino porque abajo se destructuran estos objetos para inyectarlos mezclados con otros valores.

Podemos más bien agregar un nivel más en los objetos de homologación. Por ejemplo para el background:
```js
const backgroundColor: {
  filled: {
    normal: {
      ...colors.sys.actions
    },
    hover: {
      ...hoverColors
    }
  },
  outlined: colors.ref.neutral.n0a,
  none: colors.ref.neutral.n0a,
}
```

Así, en la función `getBackgroundColor`, dados los parámetros appearance, variant, isDisabled e isHover, puede usar este objeto:
```js
function getBackgroundColor(appearance, variant, isDisabled, isHover) {
  if (variant !== "filled") {
    return backgroundColor[variant]
  }

  if (isHover) {
    return backgroundColor[variant].hover[appearance]
  }

  return backgroundColor[variant].normal[appearance]
}  

```

**Nota**: Le pedí a Leonardo que agregara el color `colors.sys.actions.disabled`. La idea es desconectar el secondary del disabled y que cada uno tenga su token de referencia.

2023-03-02 04:36 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +const appearanceBorders = {
Renombremos como `borderColors` y también agreguemos un nivel más en el objeto.

2023-03-06 20:56 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +const colorActionsSysHover = {
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e22ae93a33d98261d78b633cce1dc6ff58a98647)

2023-03-06 20:56 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e22ae93a33d98261d78b633cce1dc6ff58a98647)

2023-03-06 20:56 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +const appearanceBorders = {
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/e22ae93a33d98261d78b633cce1dc6ff58a98647)

2023-03-07 15:21 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-08 00:08 UTC, wfercanas requested changes
Aparte de los comentarios en el código, en esta PR no debería haber nada relacionado con el Spinner.

2023-03-08 00:08 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +      disabled: colors.sys.actions.disabled.stroke,
Pasa lo mismo que en backgroundColors. Está reemplazando un valor que ya trae `colors.sys.actions` y está guardando en esta ocasión sólo el stroke, mientras que las otras llaves tienen un objeto con `{filled: ..., stroke: ...}`

2023-03-08 00:08 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +  return appearanceColors[variant].normal[appearance].filled;
Si pasamos de usar los `colors.sys.actions` a los `colors.sys.text` aquí habría que refactorizar. 

De hecho quizá quede más fácil de leer esta función, pues se lee algo raro que en validación `(variant === "filled)` no se retorna `.filled` y aquí al final sí se retorna `.filled`. Leyendo el código a detalle se entiende por qué, pues en un caso tiene los tokens de referencia directo y por la otra vía tiene que acceder al .filled del token de sistema que corresponda, pero igual es raro de leer a la primera.

2023-03-08 00:11 UTC, wfercanas requested changes

2023-03-08 00:11 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +    return borderColors[variant].hover[appearance];
El border color del secondary.outlined cuando está en hover está mucho más claro de lo que está en los mockups. Casi no se ve

2023-03-08 16:57 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +const appearanceColors = {
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/85ce315c892760aeaef400744527b97d0ddcda18)

2023-03-08 16:58 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      disabled: colors.sys.actions.disabled.stroke,
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ca3c5ea139532333e395876a48a865a0bdcef7b6)

2023-03-08 16:58 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      ...colors.sys.actions,
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/4398f571b5f5a2ce84e60490607d6562cf23cfdf)

2023-03-08 16:59 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      secondary: colors.ref.palette.neutral.n900,
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9f299784c32a9e9855320bdea46871e876e95ce5)

2023-03-08 16:59 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +      disabled: colors.sys.actions.disabled.stroke,
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9f299784c32a9e9855320bdea46871e876e95ce5)

2023-03-08 16:59 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +  return appearanceColors[variant].normal[appearance].filled;
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/f883aeb1230888d1e0d947457853fdd3b920b226)

2023-03-08 17:00 UTC, cmarin001 commented on src/components/inputs/Button/styles.js
> +    return borderColors[variant].hover[appearance];
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/f883aeb1230888d1e0d947457853fdd3b920b226)

2023-03-08 19:19 UTC, Andresbl123 commented
ajustes realizados, cumple con requerimientos

2023-03-08 22:00 UTC, wfercanas approved these changes

2023-03-08 22:01 UTC, merged