Create <TextField />
selsa-inube/design-system pull request #55
Opened 2023-02-27 20:16 UTC by Andresbl123

A text field is an input that allows a user to write or edit text.

2023-03-08 00:18 UTC, wfercanas requested changes
Con Leonardo le hicimos ajustes al border y al background color del input. Revise con él y haga los ajustes al componente.

En resumen, aclaramos los bordes y agregamos un background color.

2023-03-08 18:29 UTC, wfercanas requested changes

2023-03-08 18:29 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +const stateLabel = (firstProps, secondProps) => {
No se sabe con sólo leer la función que es `firstProps` y qué es `secondProps`. Renombrar con un título más adecuado para el valor que se recibe.

2023-03-08 18:29 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +        <StyledErrorMensaje
Puede usar un <Text /> y calcular las props que le va a pasar.

2023-03-09 14:45 UTC, cmarin001 commented on src/components/inputs/TextField/index.jsx
> +const stateLabel = (firstProps, secondProps) => {
la ultima propiedad de typesInput es 'tel', sin embargo, creo que deberia ser algo como 'phone' teniendo en cuenta que el codigo esta en ingles

2023-03-09 16:14 UTC, wfercanas requested changes

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  if (isInvalid && errorMessage) {
Aquí estamos obligando a que el implementador defina un `errorMessage` si quiere usar el state `invalid`.

Yo sí creo que es buena práctica que se defina ese `errorMessage`, pero de aquí a 5 años me imagino a un desarrollador senior diciendole a otro junior "es que si no define un errorMessage no le funciona" y ya me parece un conocimiento medio oculto que no me termina de cuadrar. Dejemos que sólo dependa de la prop `isInvalid`.

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  if (isIvalid && errorMessage) {
Aquí dice isIvalid, sería `isInvalid`. Pasa lo mismo arriba en los parámetros de la función.

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  let appearance = "dark";
Creo que esta definición de la variable puede sobrar. En cada if podría hacer el return de una y al final si no pasa nada retornar el "dark".

```js
if (isDisabled) {
  return "disabled"
}
```

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  if (isInvalid && errorMessage) {
De hecho, creo que con este cambio quizá ni siquiera necesitemos esta función.

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextFaild.Required.stories.js
> +import { TextField } from "..";
El nombre de este archivo quedó incorrecto.

2023-03-09 16:14 UTC, wfercanas commented on src/components/inputs/TextField/stories/stories.stiles.js
> +import styled from "styled-components";
El nombre de este archivo quedó mal, es `styles`

2023-03-09 16:17 UTC, wfercanas requested changes

2023-03-09 16:17 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  let appearance = "dark";
De hecho, si quitamos la restricción del `errorMessage`, podríamos hacer un objeto de homologación en lugar de una función:
```js
const appearancesHomologation = {
 isDisabled: "disabled",
 isFocused: "primary,
  //...
}
```

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +import { Text } from "../../data/Text/index";
Resuelto

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +const typesInput = ["text", "email", "number", "password", "search", "tel"];
Resuelto

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +const invalidState = (isInvalid, errorMessage) => {
Resuelto

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +  if (isInvalid && errorMessage) {
Resuelto, se refactoriza la función, y con esta se evita el uso de una ternaria en la props state del componente Label

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +  let appearance = "dark";
Resuelto se refactoriza la función, con el objeto no se podría indicar el estado para el componente Text.

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +  if (isIvalid && errorMessage) {
Resuelto

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextFaild.Required.stories.js
> +import { TextField } from "..";
Resuelto

2023-03-09 20:37 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/stories.stiles.js
> +import styled from "styled-components";
Resuelto

2023-03-10 02:22 UTC, wfercanas requested changes

2023-03-10 02:22 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +          isFocused={transformedIsFocused}
Aquí creo que no supimos anticipar el diseño del focus. Si hacemos click sobre los inputs, no ocurre nada (de hecho, en los estilos tenemos para el :focus un outline: none;).

Sin embargo, en los diseños del componente sí hay un outline cuando se hace click sobre el input y de hecho el texto del label también se ve modificado. Por lo tanto:

1. Podríamos quitar por ahora esta prop de isFocused y más bien crear un estado con ese mismo nombre.
2. Adicionalmente, habría que crear una función handleFocus que modifique el estado de isFocused usando setIsFocused (useState).
3. Esta función deberían pasarse al input a través de dos eventos: onFocus y onBlur.
4. Cuando ocurra un onFocus deberíamos obtener un isFocused === true, en el otro caso tendríamos un false.
5. Este estado nos sirve entonces para pasarlo al Label, de tal forma que se prenda y se apague sincronizadamente con el outline del input.

2023-03-10 02:22 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  label: PropTypes.string.isRequired,
label no debería ser required, ya que puede haber inputs sin label (ej: search).

2023-03-10 02:22 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Invalid.stories.js
> +import { TextField } from "..";
Este componente es un componente controlado, por lo que su value y su handleChange debe administrarlo un componente controlador.

Para ese efecto, dentro de stories/ creemos un componente de react: `<TextFieldController />`. Este componente es el que vamos a usar para definir el estado y el handleChange del `<TextField />` que vayamos a representar en cada historia.

Para ver un ejemplo de implementación se puede consultar el `<Switch />`

2023-03-10 02:24 UTC, wfercanas requested changes

2023-03-10 02:24 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  disabled: ${({ isDisabled }) => isDisabled};
`disabled` no es una propiedad de CSS.

2023-03-20 21:13 UTC, wfercanas requested changes

2023-03-20 21:13 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
Separemos este componente en **index.jsx** e **interface.jsx**. En index dejamos la lógica y en interface dejamos el JSX.

Acá hay un ejemplo sencillo: https://github.com/selsa-inube/linpar/tree/main/src/components/Header

2023-03-20 21:13 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +const getAppearanceValid = (isDIsabled) => {
Dice isDIsabled, debería ser `isDisabled`

2023-03-20 21:13 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +    if (inputValue != value) {
Usar comparaciones estrictas, `!==`

2023-03-20 21:13 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  const [inputValue, setInputValue] = useState(value);
Aquí ya se sabe implícitamente que el valor ser captura usando el input, por lo que es mejor simplificar a `value` y `setValue`

2023-03-21 20:46 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +import { AiFillCheckCircle } from "react-icons/ai";
Resuelto

2023-03-21 20:46 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +const status = ["valid", "invalid", "pending"];
Resuelto

2023-03-21 20:46 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +const getAppearanceValid = (isDIsabled) => {
Resuelto

2023-03-21 20:46 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextField.Default.stories.js
> +  title: "inputs/textField/Default",
Resuelto

2023-03-22 00:56 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +    if (inputValue != value) {
Resuelto

2023-03-22 00:57 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +  const eventos = (event) => {
Resuelto

2023-03-22 14:36 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  const handleBlur = () => setIsFocused(false);
Este estado y estos handlers están definidos tanto aquí como en interface, deberían estar sólo en index.

2023-03-22 21:17 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +import { AiFillCheckCircle } from "react-icons/ai";
Resuelto

2023-03-22 21:48 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +    if (inputValue != value) {
Resuelto

2023-03-22 21:49 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +  const handleBlur = () => setIsFocused(false);
Resuelto

2023-03-23 15:03 UTC, wfercanas requested changes

2023-03-27 14:18 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TexfieldController.jsx
Resuelto

2023-03-27 14:18 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/stories.styles.js
> +const StyledFlex = styled.div`
Resuelto

2023-03-27 14:18 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +      onFocus={handleFocus}
Resuelto

2023-03-27 20:59 UTC, wfercanas requested changes

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +  const handleClickEvents = () => {
Aquí hay que hacer algunos cambios:
1. Esta función podemos rebautizarla, pues realmente no está haciendo nada con ningún event.
2. Esta función la estamos pasando con una prop handleClick al input. Esto puede ser problemático pues lo que quiere hacer esta función es manejar el focus, no el click. Por un lado uno no se espera este comportamiento por fuera del focus y por otro lado, puede ser que en un disabled o algo así, el usuario haga click y se prenda en focus no porque se dispare el onFocus, sino porque se dispara el onClick.

**Nota**: sugiero crear una función que se llame interceptFocus(), que por dentro primero haga el setIsFocused(true) y luego ejecute handleFocus()

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +      handleClick={handleClickEvents}
No usemos esta prop de handleClick salvo que vayamos a pasar algo directamente relacionado con la acción de hacer click, no de hacer focus.

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/index.jsx
> +    handleBlur,
En la función handleClickEvents() propuse unos cambios, entre ellos el crear una función que primero hace el set del focus y luego sí ejecuta el handleFocus().

Con el handleBlur habrá que hacer algo parecido, pues cuando el input pierda el focus hay que aplicar el setIsFocused(false) y luego ejecutar el handleBlur()

Nota: de hecho, en la historia default, si escribo "fer" y me salgo del input (blur), aparece correctamente que el input ha sido validado, pero permanece el focus blue sobre el textfield.

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +import { MdCheckCircle } from "react-icons/md";
Estos dos imports se pueden resumir en uno.

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +const Succes = (props) => {
Se escribe: "Success"

2023-03-27 20:59 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +};
Estas dos funciones podemos resumirlas en una sola. También el título puede hacer referencia a que estamos obteniendo una prop para Text (algo así como `getTextAppearanceProp()`)

2023-03-28 20:33 UTC, Andresbl123 commented on src/components/inputs/TextField/index.jsx
> +    handleBlur,
Resuelto

2023-03-29 15:28 UTC, wfercanas requested changes

2023-03-29 15:28 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +  const { value = "", state = "pending" } = props;
El value y el state no son datos que el TextFieldController reciba por props.

Hagamos de cuenta que el TextFieldController realmente es un formulario que por dentro tiene sólo un input. El formulario crea el estado con el cual va a administrar los valores y los cambios de esos valores en los inputs. También con el estado va a controlar si un input está pending, success o invalid.

**Conclusión**: no pasemos el value y el state por props.

2023-03-29 15:28 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +  const [globalState, setGlobalState] = useState(state);
En lugar de crear estos dos estados separados, creemos un sólo estado. Podemos crearlo como form y setForm.
Ahora, la inicialización del estado es un objeto, donde tiene las llaves value y state, de tal forma que puede controlar al input con este objeto.

El value y el state de este objeto es lo que finalmente le pasa a `<TextField />`

2023-03-29 15:28 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +    setValueInput(e.target.value);
Cuando hay un change, no solamente hay que cambiar el value del estado, también hay que cambiar el state del estado a "pending".

Esto permite que si, por ejemplo, el input está invalid porque puse números en lugar de letras y yo borro un dígito, el campo deje de ser invalid. Luego, cuando haga el blur, volvemos a validar y si sigue invalid, vuelve y se pone rojo.

2023-03-29 20:17 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +  const { value = "", state = "pending" } = props;
Se deja estos valores como props para ajustar el contenido de las historias a los mockups, donde hay un estado o valor inicial diferentes a los que el componente tiene por default

2023-03-29 20:18 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +    setValueInput(e.target.value);
Resuelto

2023-03-30 02:47 UTC, wfercanas requested changes

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextfieldController.jsx
> +  const { value = "", state = "pendeging" } = props;
Es "pending"

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  cursor: ${({ isDisabled }) => (isDisabled ? "no-drop" : "context-menu")};
Estos cursores están raros. Yo creo que no van, valide con Leonardo.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +    succes: "success",
Es "success"

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +const fontSize = (size) => {
Sigamos con la estructura de abajo y dejemos `getFontSize()`

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +    height: 20px;
Este height rompe el `align-items: center`, sobre todo en size "compact"

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +    font-size: ${({ size }) => fontSize(size)};
No es necesario definir estas propiedades tipográficas del label aquí, el `<Label />` ya recibe la prop typo. Puede definir esa prop en el return de **interface.jsx**

Para eso debe tomar los cambios recientes de main.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  display: flex;
Preferiría que usaramos un `display: grid`.
Con eso podríamos:
1. No usar position relative y absolutes para organizar el input y los iconos.
2. No hacer enredados los estilos flex del input. De hecho el input no necesitaría tener estilos de este tipo.
3. Los StyledIcon no tienen por qué se grillas, simplemente es un ícono y ya, que usa una celda de la tabla que cree StyledContainerLabel
4. La grilla de StyledContainerLabel sería máximo de 3 columnas, con `grid-template-columns: auto 1fr auto;`
5. Este template-columns habría que evaluarlo según si hay o no hay íconos.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  width: ${({ isRequired }) => (isRequired ? "115px" : "51px")};
El ancho no debería depender de si es required o no.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +const StyledInput = styled.input`
Este componente tiene muchos estilos relacionados a flex y que sobran:
1. Un input no es un container, por lo que no tiene sentido que sea display: flex
2. Si es un flex-container, no tiene sentido tener flex-direction ni align-items
3. Usa flex y luego usa flex-grow. La propiedad flex ya está resumiendo en parte a flex-grow, luego se está sobreescribiendo.

En el container usemos la grid propuesta y simplifiquemos así los estilos de este input.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  position: absolute;
Estamos usando position para ubicar los íconos dentro del container. Esto es problemático de mantener.
Usemos la grid propuesta arriba y estos abosolute, right, left, sobran.

2023-03-30 02:47 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  position: relative;
Si quitamos los absolute de abajo, ya no es necesario que este componente sea `relative`.

2023-04-04 20:59 UTC, wfercanas requested changes

2023-04-04 20:59 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +  return appearenceMap[appearence] || "dark";
Entiendo que appearance es un string, luego estaríamos tomando un string, para leer un objeto con ese string que al final devuelve el mismo string del principio.
Podríamos simplificar y reteornar directamente "appearance".

2023-04-04 20:59 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Default.stories.js
Esta historia no es required. Sin embargo, cuando hago focus y luego blur, se prende con un error.

2023-04-04 20:59 UTC, wfercanas commented on src/components/inputs/TextField/styles.js
> +  cursor: ${({ isDisabled }) => isDisabled && "no-drop"};
En lugar de no-drop, usemos not-allowed.

2023-04-04 20:59 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Number.stories.js
1. Cuando se digita el número y se hace blur, sale un error vacío.
2. El campo no es requerido y si se hace focus + blur, aparece un error.

2023-04-04 20:59 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Search.stories.js
1. El fondo del ícono es diferente al fondo del input.
2. El ícono está pegado a la izquierda, luego si el texto es muy largo, va a quedar el ícono tocando el texto.
3. El input está pegado al borde izquierdo del container y no se ve bien.

2023-04-10 14:25 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Search.stories.js
Este error aún está presente

2023-04-10 14:31 UTC, wfercanas requested changes

2023-04-10 14:31 UTC, wfercanas commented on src/components/inputs/TextField/stories/TextField.Search.stories.js
El search sigue teniendo problemas de estilos, el fondo no del ícono no se corresponde con el fondo del input.

2023-04-10 22:24 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextField.Search.stories.js
Resuelto

2023-04-10 22:24 UTC, Andresbl123 commented on src/components/inputs/TextField/stories/TextField.Number.stories.js
Resuelto

2023-04-12 16:27 UTC, wfercanas requested changes

2023-04-12 16:27 UTC, wfercanas commented on src/components/inputs/TextField/interface.jsx
> +      <StyledContainerLabel wrap="wrap" size={size} isDisabled={isDisabled}>
El label está pegado al Input. En los mockups hay una distancia de 4px entre uno y otro.

2023-04-12 21:10 UTC, wfercanas approved these changes

2023-04-12 21:10 UTC, merged