Cm/ids5/use media query
selsa-inube/design-system pull request #56
Opened 2023-03-01 22:26 UTC by cmarin001

2023-03-02 15:33 UTC, Andresbl123 commented on src/hooks/stories/Example.stories.js
> +import { SwitchController } from "./../../components/inputs/Switch/stories/SwitchController";
al cambiar el estado en la historia de ejemplo me sale el siguiente error, esto no pasa al validar las historias del componente Switch

2023-03-02 15:33 UTC, Andresbl123 commented on src/hooks/useMediaQuery.js
> +export default useMediaQuery;
creo que se podría cambiar el export default, solo por export, así se fuerza la importación del hook con su nombre y no con un alias

2023-03-02 15:47 UTC, cmarin001 commented on src/hooks/useMediaQuery.js
> +export default useMediaQuery;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ca1fb4a193e0aec07ded270fbc0c0bfaf7ce6b7a)

2023-03-06 17:48 UTC, wfercanas requested changes
Además del cambio en el fuente, hay que ajustar el conflicto que hay en git

2023-03-06 17:48 UTC, wfercanas commented on src/hooks/useMediaQuery.js
> +    const handleChange = () => setMatches(mediaQuery.matches);
La definición de la función es mejor por fuera del useEffect, si no por cada ejecución del effect se crea un nuevo `handleChange`

2023-03-06 19:46 UTC, cmarin001 commented on src/hooks/useMediaQuery.js
> +    const handleChange = () => setMatches(mediaQuery.matches);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/763a3726f1002a52760a72b0495c0e3525b6c278)

2023-03-06 21:09 UTC, Andresbl123 commented on src/hooks/useMediaQuery.js
> +    const handleChange = () => setMatches(mediaQuery.matches);
creo que no tiene las últimas actualización que se hicieron en main, y por lo cual podría generar conflictos al integrar la rama, del resto cumple con los requerimientos

2023-03-06 21:12 UTC, cmarin001 commented on src/hooks/useMediaQuery.js
> +    const handleChange = () => setMatches(mediaQuery.matches);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/3e092dbc5a35551d4d17ac309565c1dad00872f4)

2023-03-07 14:01 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-08 18:08 UTC, wfercanas commented on src/hooks/useMediaQuery.js
> +export default useMediaQuery;
Esta sugerencia es válida y sigue pendiente. Es mejor hacer un export nombrado.

2023-03-08 19:38 UTC, cmarin001 commented on src/hooks/useMediaQuery.js
> +export default useMediaQuery;
incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/771aacd09b6626906cfba44e5d2a078a9f30d1da)

2023-03-08 20:50 UTC, Andresbl123 commented
falta actualizar los últimos cambios realizados en la rama main,, para evitar conflictos en la integración

2023-03-08 21:06 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-08 21:12 UTC, wfercanas approved these changes

2023-03-08 21:12 UTC, merged