feat(exportComponents): added export for the components button, spinn…
selsa-inube/design-system pull request #60
Opened 2023-03-08 22:35 UTC by cmarin001

…er and the hook usemediaquery

2023-03-09 14:15 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-09 15:35 UTC, wfercanas requested changes

2023-03-09 22:36 UTC, cmarin001 commented on src/index.js
> +export { useMediaQuery } from "./../useMediaQuery";
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/3d5c533b4496d008ae6649d30a653caed769c188)

2023-03-09 23:01 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-10 02:26 UTC, wfercanas approved these changes

2023-03-10 02:26 UTC, merged