feat(user): added user-component
selsa-inube/design-system pull request #63
Opened 2023-03-13 16:47 UTC by cmarin001

2023-03-14 13:29 UTC, Andresbl123 commented on src/components/data/User/stories/User.Default.stories.js
> +export const Default = (args) => <User {...args} />;
validar la historia, ya que el componente no se  muestra como debe ser

2023-03-14 13:29 UTC, Andresbl123 commented on src/components/data/User/styles.js
> +    color: ${colors.ref.palette.neutral.n900};
para el color del texto en figma se recomienda usar, Username: colors.sys.text.dark

2023-03-14 13:29 UTC, Andresbl123 commented on src/components/data/User/styles.js
> +    color: ${colors.ref.palette.neutral.n300};
para el color del texto en figma se recomienda usar: Business unit: colors.sys.text.secondary

2023-03-14 13:41 UTC, cmarin001 commented on src/components/data/User/styles.js
> +    color: ${colors.ref.palette.neutral.n300};
Incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/13b9e1d967bfea860852c627c283e3691c0d1715)

2023-03-14 13:41 UTC, cmarin001 commented on src/components/data/User/styles.js
> +    color: ${colors.ref.palette.neutral.n900};
Incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/13b9e1d967bfea860852c627c283e3691c0d1715)

2023-03-14 13:44 UTC, cmarin001 commented on src/components/data/User/stories/User.Default.stories.js
> +export const Default = (args) => <User {...args} />;
Incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/fd45a734f6a9b2ec1ca8fac1a963756d3ec5cc97)

2023-03-14 13:59 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-14 14:43 UTC, wfercanas requested changes

2023-03-14 14:43 UTC, wfercanas commented on src/components/data/User/index.jsx
> +  const fixedSize = sizes.includes(size) ? size : defaultSize;
En otros componentes hemos usado `transformedSize`, mantengamos ese uso.

2023-03-14 14:43 UTC, wfercanas commented on src/components/data/User/index.jsx
> +        <span id="businessUnit">{businessUnit}</span>
En lugar de usar span directos, puede usar `<Text as="span" />`, así en un futuro también pueden usarse aquí los tokens de sistema para texto.

2023-03-14 14:43 UTC, wfercanas commented on src/components/data/User/index.jsx
> +      <StyledCard>
Si usa `<Text />` abajo, los estilos de este styled-component no requieren definir tipografía. Como ya no necesita tipografía se queda sólo con el `display:flex`, cosa que se puede hacer con un `<Stack />`

2023-03-14 14:43 UTC, wfercanas commented on src/components/data/User/stories/User.Default.stories.js
> +import React from "react";
Cuando la prop size es small, se muestra sólo el `<Avatar />`, sin texto.

2023-03-14 16:27 UTC, cmarin001 commented on src/components/data/User/index.jsx
> +  const fixedSize = sizes.includes(size) ? size : defaultSize;
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/16b10a5d4bd225e96e628dcc18807ad8662946e0)

2023-03-14 16:28 UTC, cmarin001 commented on src/components/data/User/index.jsx
> +        <span id="businessUnit">{businessUnit}</span>
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/24074c51daf352a6fe64df47bab6a1a2353fcf3b)

2023-03-14 16:28 UTC, cmarin001 commented on src/components/data/User/index.jsx
> +      <StyledCard>
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/8e2a5302a20611422fb26122a84f65806bd2e225)

2023-03-14 16:29 UTC, cmarin001 commented on src/components/data/User/stories/User.Default.stories.js
> +import React from "react";
para este caso eso fue lo que habiamos acordado y tambien es algo que esta especificado en el documento 
![image](https://user-images.githubusercontent.com/45011420/225072935-f6cb1bda-623a-4c88-a925-468991e08a84.png)

2023-03-15 14:38 UTC, Andresbl123 commented
Cumple con los requerimientos, Se pasa la ultima observación sobre las props, ya que el desarrollo se ajusta a los requerimientos del documento.

2023-03-15 19:35 UTC, cmarin001 commented on src/components/data/User/stories/User.Default.stories.js
> +import React from "react";
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/007757b5ac3e151df67242edff675f0c01382ff2)

2023-03-15 23:38 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-16 02:57 UTC, wfercanas approved these changes

2023-03-16 02:58 UTC, merged