ab/ids21/SkeletonLine
selsa-inube/design-system pull request #64
Opened 2023-03-14 01:09 UTC by Andresbl123

The SkeletonLine component with its history is implemented

2023-03-14 14:54 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +  background: linear-gradient(
incidencia resualta

2023-03-14 19:28 UTC, wfercanas requested changes

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/index.jsx
> +  with: PropsTypes.string,
Esta prop es `width`, no `with`

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/index.jsx
> +import PropsTypes from "prop-types";
El import es de `PropTypes`, no de `PropsTypes`

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/index.jsx
> +SkeletonLine.propsTypes = {
Es `SkeletonLine.propTypes`

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +  @keyframes shimmer {
La animación la puede crear aparte, usando `const shimmer = keyframes`. Previo a eso tendría que hacer `import { keyframes } from 'styled-components'`.

https://styled-components.com/docs/basics#animations

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +  animation: shimmer 2s linear infinite;
Esta regla podría evaluar si `animation === true`. En ese caso usa `shimmer` con las demás propiedades, si no no hace nada.

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +const StyledProgressSkeleton = styled.h2`
No hay razón semántica para que este componente sea un `h2`.

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +  content: "";
Esta regla de `content: ""` se usa generalmente acompañada con los pseudoelementos `::before` o `::after`. Lo normal sería que StyledSkeletonLine fuera la línea gris normal y si existe animación, usar un pseudoelemento de estos para lograr el efecto.

2023-03-14 19:28 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +const StyledSkeletonLine = styled(StyledProgressSkeleton)`
Si se implementa un pseudoelemento, no haría falta extender los estilos de un styled-component para anidar la animación. Esos estilos serían propios de un `&::before` por ejemplo.

2023-03-14 22:09 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/index.jsx
> +  with: PropsTypes.string,
resuelto

2023-03-14 22:09 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/index.jsx
> +import PropsTypes from "prop-types";
Resuelto

2023-03-14 22:09 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/index.jsx
> +SkeletonLine.propsTypes = {
Resuelto

2023-03-14 22:09 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +  @keyframes shimmer {
Resuelto

2023-03-14 22:10 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +  animation: shimmer 2s linear infinite;
Resuelto

2023-03-14 22:10 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +const StyledProgressSkeleton = styled.h2`
Resuelto

2023-03-14 22:11 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +  content: "";
Resuelto

2023-03-14 22:11 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +const StyledSkeletonLine = styled(StyledProgressSkeleton)`
resuelto

2023-03-15 16:09 UTC, cmarin001 commented on src/components/feedback/SkeletonLine/styles.js
> +import { keyframes } from "styled-components";
esta linea se puede simplificar de la siguiente manera import styled, { keyframes } from "styled-components";

2023-03-15 18:43 UTC, wfercanas requested changes

2023-03-15 18:43 UTC, wfercanas commented on src/components/feedback/SkeletonLine/styles.js
> +      ${colors.ref.palette.neutralAlpha.n10A} 50%,
Subamos a n20a para que se note un poquito más la animación.

2023-03-15 19:21 UTC, Andresbl123 commented on src/components/feedback/SkeletonLine/styles.js
> +      ${colors.ref.palette.neutralAlpha.n10A} 50%,
Resuelto

2023-03-16 03:01 UTC, wfercanas approved these changes

2023-03-16 03:03 UTC, merged