cm/ids28/switch
selsa-inube/design-system pull request #66
Opened 2023-03-16 20:46 UTC by cmarin001

2023-03-17 14:32 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-20 16:48 UTC, wfercanas requested changes

2023-03-21 16:04 UTC, cmarin001 commented on src/components/inputs/Switch/stories/props.js
> +  description: "component text content",
Incidencia resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/4aa4dfffe4a5baa6a59fb9f96c7282562e627ffa)

2023-03-21 21:56 UTC, Andresbl123 commented
cumple con los requerimientos

2023-03-22 14:01 UTC, merged