cm/ids30/tab
selsa-inube/design-system pull request #68
Opened 2023-03-22 21:21 UTC by cmarin001

2023-03-22 22:38 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-23 01:48 UTC, wfercanas requested changes

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/index.jsx
> +  const transformedHandleClick = isDisabled ? undefined : handleClick;
Es preferible que al evento onClick le pasemos una función que evalúa si la <Tab /> está habilitada o no antes de ejecutar el handler, a pasarle a veces una función y a veces `undefined`.

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/index.jsx
> +        {children}
En el diseño de `<Tabs />` hice unas observaciones sobre la prop `children` que detalló en el documento para ese componente. Puede ser que si allá finalmente terminamos usando una estructura de datos para la lista de `<Tab />` a pintar, esa estructura traiga dentro de sus atributos el label del tab.

Lo digo porque si allá lo bautizamos como label a esa propiedad, podríamos pasarsela al componente `<Tab />` también como prop `label` y no vía `children`.

Revíselo.

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/stories/TabController.jsx
> +    handleClick(!tabSelected);
Esta función `handleClick` en la historia equivale a una arrow function vacía. Luego no hace nada.
Es suficiente con que el `Controller` tenga la función handleClickTab y se la pase a `<Tab />` usando la prop `handleClick`

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/stories/TabController.jsx
> +    console.log("handleClick: ", !tabSelected);
Podemos borrar este `console.log()`

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/stories/Tab.Default.stories.js
> +  children,
Si vamos a usar `children`, es preferible que TabController le pase a Tab el texto como `<Tab>General Information</Tab>`. Si no, es mejor usar una prop diferente a `children`.

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/index.jsx
> +    <StyledContainer
Podríamos rebautizar este contenedor como `StyledTab`

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/styles.js
> +  user-select: none;
En el diseño no estaba que el texto de la `<Tab />` no se pudiera seleccionar. ¿Por qué agregarlo?

2023-03-23 01:48 UTC, wfercanas commented on src/components/navigation/Tab/styles.js
> +  display: inline-block;
Si luego hacemos que `<Tabs />` sea un contenedor flex, no haría falta que la `<Tab />` sea `inline-block`, ni que modifiquemos su position. La `<Tab />` sería un `flex-item`.

2023-03-23 17:11 UTC, cmarin001 commented on src/components/navigation/Tab/index.jsx
> +        {children}
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/6fbdd4aba3c1a2575fd733f23e3e34c8b518d9f1)

2023-03-23 17:12 UTC, cmarin001 commented on src/components/navigation/Tab/stories/TabController.jsx
> +    handleClick(!tabSelected);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/6fbdd4aba3c1a2575fd733f23e3e34c8b518d9f1)

2023-03-23 17:12 UTC, cmarin001 commented on src/components/navigation/Tab/stories/TabController.jsx
> +    console.log("handleClick: ", !tabSelected);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/77050593090988f9925ddfaf0d294d038530b62f)

2023-03-23 17:12 UTC, cmarin001 commented on src/components/navigation/Tab/stories/Tab.Default.stories.js
> +  children,
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/6fbdd4aba3c1a2575fd733f23e3e34c8b518d9f1)

2023-03-23 17:13 UTC, cmarin001 commented on src/components/navigation/Tab/index.jsx
> +    <StyledContainer
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/b8e601a445110eb310a1002fad94bd08f064da38)

2023-03-23 17:16 UTC, cmarin001 commented on src/components/navigation/Tab/styles.js
> +  user-select: none;
Aqui decidi agregarlo por que al dejarlo como viene por default puede causar un comportamiento que puede ser problematico
![image](https://user-images.githubusercontent.com/45011420/227283755-2323b703-9824-4df2-881e-a20b797672b3.png)
![image](https://user-images.githubusercontent.com/45011420/227283826-17a7835d-5bcc-4343-88e8-25f844b19d99.png)

Aunque inicalmente no estaba contemplado creo que es algo necesario para evitar que cuando se de click repetidamente ocurra lo que muestro en las imagenes arriba

2023-03-24 14:26 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-27 20:16 UTC, wfercanas requested changes

2023-03-27 20:16 UTC, wfercanas commented on src/components/navigation/Tab/stories/TabController.jsx
> +  const { isSelected = false, handleClick, isDisabled = false } = props;
Este componente no necesita recibir por props la función **handleClick**.
Como es el componente controlador, es en este componente donde se define esa función.

Tampoco hace falta recibir la prop **isSelected**, eso también lo define el controlador al crear el estado.

2023-03-27 20:16 UTC, wfercanas commented on src/components/navigation/Tab/stories/Tab.Default.stories.js
> +  handleClick: () => {},
Esta función, que no se va a usar nunca, es mejor borrarla.

2023-03-27 20:38 UTC, cmarin001 commented on src/components/navigation/Tab/stories/TabController.jsx
> +      handleClick(!tabSelected);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/9f2c6d74e534a7d01fd026e6f4c384a80d054873)

2023-03-28 01:13 UTC, Andresbl123 commented on src/components/navigation/Tab/stories/TabController.jsx
> +  const { isSelected = false, handleClick, isDisabled = false } = props;
En esta parte sigue recibiendo la props de isSelected, el controller, creo que se podría evitar desde el mismo estado, algo como: 
  const { isDisabled = false } = props;
  const [isSelected, setIsSelected] = useState(false);
y ya se maneja la constante isSelected en las funciones

2023-03-28 13:15 UTC, cmarin001 commented on src/components/navigation/Tab/stories/TabController.jsx
> +  const { isSelected = false, handleClick, isDisabled = false } = props;
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/47d7ac08cde4d27e64db31a0b1c267445795f869)

2023-03-28 14:23 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-28 15:49 UTC, wfercanas commented on src/components/navigation/Tab/stories/TabController.jsx
> +      setTabSelected(!tabSelected);
Cuando se hace click sobre el Tab, solamente debería ponerse en true el selected. Si permitimos que el click sobre el selected apague la selección, tendríamos unas Tabs con nada seleccionado y por ende un espacio blanco abajo de las Tabs, sin contenido.

**Conclusión**: hacer click implica seleccionar, nunca deseleccionar.

2023-03-28 15:50 UTC, wfercanas commented on src/components/navigation/Tab/index.jsx
> +    <StyleTab
Cambiar por `StyledTab`

2023-03-28 17:30 UTC, cmarin001 commented on src/components/navigation/Tab/index.jsx
> +    <StyleTab
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/595a448510745b419e59e3b7b7d6d14a8f309535)

2023-03-28 17:36 UTC, cmarin001 commented on src/components/navigation/Tab/stories/TabController.jsx
> +      setTabSelected(!tabSelected);
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/72b1cda8d6e02e69a538fa3bc0692dd09fdcf1e4)

2023-03-28 20:56 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-03-28 21:24 UTC, wfercanas requested changes

2023-03-28 21:24 UTC, wfercanas commented on src/components/navigation/Tab/styles.js
> +const StyledTab = styled.div`
Hagamos de este componente un `li`, que luego estaría anidado en un `ul` (Tabs)

2023-03-28 21:24 UTC, wfercanas commented on src/components/navigation/Tab/stories/TabController.jsx
> +    <Tab {...props} isSelected={tabSelected} handleClick={handleClickTab} />
En {...props} estamos pasando sólo isDisabled, por lo que quedaría más legible si le pasamos de una el isDisabled y ya, sin destructurar.

2023-03-28 21:44 UTC, cmarin001 commented on src/components/navigation/Tab/styles.js
> +const StyledTab = styled.div`
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/26fb502b49e566f8c81336db42727422ce33e661)

2023-03-28 21:51 UTC, wfercanas approved these changes

2023-03-28 22:18 UTC, merged