Ab/ids33/label typography
selsa-inube/design-system pull request #71
Opened 2023-03-27 20:30 UTC by Andresbl123

This pull request adds support for a typo prop to the component. This prop allows us to specify the kind of typography to use for the label, choosing from the labelLarge, labelMedium, or labelSmall options defined in our typography system.

2023-03-27 21:55 UTC, wfercanas requested changes

2023-03-27 21:55 UTC, wfercanas commented on src/components/inputs/Label/stories/Label.Default.stories.js
> +  typo: "labelLarge",
No hace falta definir esta arg si typo tiene un valor por default.

2023-03-27 21:55 UTC, wfercanas commented on src/components/inputs/Label/styles.js
>    letter-spacing: ${typography.sys.typescale.labelLarge.tracking};
Faltan propiedades del rol label en typography: line-height, font-weight.

2023-03-27 21:55 UTC, wfercanas commented on src/components/inputs/Label/stories/Label.Size.stories.js
> +        <div>
Este `div` sobra

2023-03-27 21:55 UTC, wfercanas commented on src/components/inputs/Label/stories/Label.Size.stories.js
> +          <Label
Aquí hace falta la prop `key` por estar dentro de un map.

2023-03-27 23:41 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.Default.stories.js
> +  typo: "labelLarge",
Resuelto

2023-03-27 23:42 UTC, Andresbl123 commented on src/components/inputs/Label/styles.js
>    letter-spacing: ${typography.sys.typescale.labelLarge.tracking};
Resuelto

2023-03-27 23:42 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.Size.stories.js
> +        <div>
Resuelto

2023-03-27 23:42 UTC, Andresbl123 commented on src/components/inputs/Label/stories/Label.Size.stories.js
> +          <Label
Resuelto

2023-03-28 15:40 UTC, wfercanas requested changes
Cambiemos el título de la Pull Request para que nos empiece a quedar mejor armado el CHANGELOG.md

2023-03-28 21:25 UTC, wfercanas approved these changes

2023-03-28 21:25 UTC, merged