fix(stack): fixed the issue related with the spacing(width-property)
selsa-inube/design-system pull request #87
Opened 2023-03-30 16:46 UTC by cmarin001

2023-03-30 21:35 UTC, Andresbl123 commented
Cumple con el requerimiento

2023-03-31 02:24 UTC, wfercanas commented
Hagamos una historia donde se reproduzca el error que estamos intentando corregir. Yo debería poder comentar los cambios hechos al fuente del Stack y ver el error en Storybook.

2023-03-31 02:25 UTC, wfercanas commented
También cambiemos el título de esta PR, dice que se hace el fix del issue relacionado con el spacing, pero sería preferible intentar darle un título al issue

2023-03-31 19:39 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-03 16:58 UTC, wfercanas requested changes

2023-04-03 16:58 UTC, wfercanas commented on src/components/layouts/Stack/stories/stories.styles.js
> +const StyledContainer = styled.div`
Demasiado complejo para servir de ejemplo, puede ser más complejo entender qué se está haciendo aquí que lo que se está arreglando en el Stack.

Simplifiquemos para que sea rápidamente visible lo que se ajustó.

2023-04-03 16:58 UTC, wfercanas commented on src/components/layouts/Stack/stories/Stack.Implementation.stories.js
> +    <Stack gap="48px">
Un Stack con un solo hijo no tiene sentido que tenga un gap, no habría gap entre elementos porque sólo es 1 elemento.

2023-04-03 16:58 UTC, wfercanas commented on src/components/layouts/Stack/stories/Stack.Implementation.stories.js
> +      <Stack>
Este Stack también tiene sólo 1 hijo.

2023-04-03 16:59 UTC, wfercanas requested changes

2023-04-03 16:59 UTC, wfercanas commented on src/components/layouts/Stack/stories/Stack.Implementation.stories.js
El título "Implementation" no dice mucho..., si el problema a resolver es el anidamiento de stacks, se puede llamar "Nesting" la historia

2023-04-04 21:48 UTC, closed without merging