<Button /> should have a width to fit the content if isFullWidth is false
selsa-inube/design-system pull request #88
Opened 2023-03-30 21:28 UTC by Andresbl123

When the isFullWidth property is set to false, it is necessary to verify the size of the button. The button should only be concerned with the size of the text it contains and should adjust its size accordingly.

2023-03-31 02:35 UTC, wfercanas requested changes

2023-03-31 02:35 UTC, wfercanas commented on src/components/inputs/Button/styles.js
> +const getWidth = (iconBefore, iconAfter, isFullWidth) => {
No estoy de acuerdo con esta solución, me parece que estamos hardcodeando pixeles para intentar arreglar y de hecho agregamos más problemas.
Si en la historia en lugar de pasarle un children corto como "Button" le pasamos un children que diga "Realiza tu reservación", se rompe el botón.

Antes de meterle la mano al código, quiero ver una historia donde se reproduzca el error. Es decir, en el siguiente push a esta rama voy a comentar esta función y voy a poner el width como estaba antes en los estilos y quiero ver el error reproducido.

2023-04-05 16:55 UTC, Andresbl123 commented on src/components/inputs/Button/styles.js
> +const getWidth = (iconBefore, iconAfter, isFullWidth) => {
Resuelto

2023-04-10 14:09 UTC, wfercanas approved these changes

2023-04-10 14:10 UTC, merged