cm/ids41/tabs
selsa-inube/design-system pull request #89
Opened 2023-03-31 21:36 UTC by cmarin001

2023-04-02 18:34 UTC, Andresbl123 commented
falta este requerimiento: 
The component is exported from the library.

2023-04-03 19:36 UTC, wfercanas requested changes

2023-04-03 19:36 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  const [activeTab, setActiveTab] = useState(selectedTab);
Como se indicó en el diseño, este componente es un componente controlado y el estado lo debe manejar quien lo necesite en su layout.
Esto es importante porque hay que elevar el estado hasta el padre, de tal manera que el padre sepa qué debe renderizar en la pantalla según cuál es la tab seleccionada.

Dicho esto, aquí hay que eliminar el estado y ejecutar directamente el handler que recibimos por props.

2023-04-03 19:36 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  };
Si el componente no tiene ningún interés adicional al cambio de selectedTab con el onClick, es suficiente con ejecutar el handleSelectedTab directamente.

2023-04-03 19:36 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
En este componente puede ser grave que recibamos dos id iguales para dos tab diferentes. Valdría la pena por lo menos imprimir un `console.warn()` si es que en algún momento esto llega a suceder.

2023-04-05 15:56 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
Resuelto

2023-04-05 15:56 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
> +  const [activeTab, setActiveTab] = useState(selectedTab);
Resuelto

2023-04-05 15:56 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
> +  };
Resuelto

2023-04-10 15:51 UTC, wfercanas requested changes

2023-04-10 15:51 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +const duplicateTabIds = (tabs) => {
Cambiemos el nombre de esta función por `checkDuplicateTabIds`

2023-04-10 15:51 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +      throw new Error(
Si hace este `throw new Error`, la pantalla se va a romper con este mensaje de error (haga el intento con la historia, quítele el id a una de las tabs y verá). Esta parte ya la está controlando con prop-types al decir que el id isRequired.

Quitando lo anterior, la función ahora sí queda con el objetivo que es: buscar si hay duplicados.

2023-04-10 16:42 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
> +      throw new Error(
Si señor, pensé  que estaría bien por la importancia del id.
Resuelto

2023-04-10 16:42 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
> +const duplicateTabIds = (tabs) => {
Resuelto

2023-04-11 14:36 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +    if (tab.id === undefined) {
Como le decía en el comentario anterior, no hace falta revisar si el id no llega, porque para eso estamos usando las prop-types con el isRequired.
Si la función se llama checkDuplicates, debería enfocarse únicamente en validar si hay o no duplicados, que es la parte que tiene abajo.

De hecho, el console.warn podría estar aquí dentro y no en el cuerpo del componente. De esa manera el componente queda más limpio.

2023-04-12 21:27 UTC, wfercanas requested changes

2023-04-12 21:27 UTC, wfercanas commented on src/components/navigation/Tabs/index.jsx
> +  }
Dejemos esta validación y el console.warn dentro de la función `checkDuplicateTabIds()`.
Lo único que tendría que hacer Tabs es ejecutar esta función y ya, directo al `return`.

2023-04-12 23:09 UTC, Andresbl123 commented on src/components/navigation/Tabs/index.jsx
> +  }
Resuelto

2023-04-13 20:56 UTC, wfercanas approved these changes

2023-04-13 20:57 UTC, merged