Simplify the <Switch /> stories using <Stack />
selsa-inube/design-system pull request #93
Opened 2023-04-05 19:51 UTC by Andresbl123

Refactor any use of styled components to manage or deal with the display: flex property. Instead, it is recommended to use a specialised component called "Stack" that has been designed to handle these types of CSS styles and properties.

2023-04-10 15:35 UTC, wfercanas requested changes

2023-04-10 15:35 UTC, wfercanas commented on src/components/inputs/Switch/stories/Switch.WithLabel.stories.js
>          <StyledMargin key={item}>
Este `StyledMargin` si podemos eliminarlo. agrega un espacio que por ahora no es necesario.

2023-04-10 16:12 UTC, cmarin001 commented on src/components/inputs/Switch/stories/Switch.WithLabel.stories.js
>          <StyledMargin key={item}>
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/ffc406578706b593e218752331e2ede6facfee4b)

2023-04-11 14:33 UTC, wfercanas requested changes

2023-04-12 15:46 UTC, wfercanas approved these changes

2023-04-12 15:47 UTC, merged