Create <Breadcrumbs/>
selsa-inube/design-system pull request #95
Opened 2023-04-11 16:58 UTC by cmarin001

2023-04-12 15:03 UTC, Andresbl123 commented on src/components/navigation/Breadcrumbs/index.jsx
> +export { Breadcrumbs };
Hace falta este criterio: The component is exported from the library

2023-04-12 16:22 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/index.jsx
> +export { Breadcrumbs };
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/f54f1fc53776d8ef64bb08b6139d59ee1dfbde3a)

2023-04-13 14:28 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-13 22:09 UTC, wfercanas requested changes

2023-04-13 22:09 UTC, wfercanas commented on src/components/navigation/BreadcrumbLink/index.jsx
> +    </BrowserRouter>
Si agrega este `<BrowserRouter />` aquí, lo que va a ocurrir en las aplicaciones que usen el componente es que va a haber un BrowserRouter dentro de otro BrowserRouter (El de la aplicación y por dentro el de este componente).

Esto puede traer problemas en la navegación, ya que los link buscan el `<Route>` dentro del router más cercano, que en este caso es el del componente y no el de la app.

Por eso en su momento el BrowserRouter estaba en la historia, porque allá se está importando y por ende quien usa el componente debe asegurarse de que lo importa dentro de un router.

2023-04-13 23:34 UTC, cmarin001 commented on src/components/navigation/Breadcrumbs/styles.js
> +    margin: 0 5px;
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/3f5a95796c58d324ff99dc6feba9ce71cb7043a0)

2023-04-13 23:34 UTC, cmarin001 commented on src/components/navigation/BreadcrumbLink/index.jsx
> +    </BrowserRouter>
Incidencia Resuelta
[commitResolver](https://github.com/selsa-inube/design-system/commit/de5b9b33a47f7708f4b0fe33f2ac307e0c8e3507)

2023-04-14 17:53 UTC, Andresbl123 commented
Cumple con los requerimientos

2023-04-14 19:28 UTC, wfercanas approved these changes

2023-04-14 19:28 UTC, merged