Verify the <User /> component for It has an improper gap between the avatar and the text
selsa-inube/design-system pull request #97
Opened 2023-04-11 22:07 UTC by Andresbl123

The component in the header has a space between the avatar and the text that is not aligned with the layouts, this is because a width of 169px is being placed which is not maintaining the 16px gap.

2023-04-11 23:14 UTC, cmarin001 reviewed
cumple con los requerimientos

2023-04-12 16:37 UTC, wfercanas requested changes

2023-04-12 16:37 UTC, wfercanas commented on src/components/data/User/styles.js
> +  width: fit-content;
No es necesario ajustar el width si arriba no se aplica un `justify-content: space-between`. En la práctica no vamos a coger un avatar y lo vamos a mandar todo a la derecha y el texto todo a la izquierda.

Basta con quitar tanto la definición del width como con quitar el justify content. De hecho, este StyledUser sirve sólo para aplicar propiedades flex, así que podemos eliminarlo por un Stack. Antes se justificaba porque estábamos pasando una prop `size` pero ya no la vamos a usar en los estilos, así que sobraría un styled-component aquí.

2023-04-12 21:21 UTC, wfercanas approved these changes

2023-04-12 21:21 UTC, merged