Sync Label and TextField so there is no state homologation
selsa-inube/design-system pull request #98
Opened 2023-04-13 16:20 UTC by Andresbl123

BREAKING CHANGE:

Currently, the <TextField /> component has a state property that indicates whether the input is valid, invalid, or pending. However, the <Label /> component also has a state property, but it does not match the state set in the <TextField /> component. Therefore, the props of the Label component are modified and updated in the library where the component is used with props. If this change is made, it's important to note that it could potentially break the styles and behavior in places where the Label component is used. Additionally, it's recommended to update the Label component's state to align with the state of the TextField component to ensure consistency in the codebase

2023-04-14 16:13 UTC, wfercanas requested changes

2023-04-14 16:13 UTC, wfercanas commented on src/components/inputs/Label/index.jsx
> +    typeof isInvalid === "boolean" ? isInvalid : defaultIsInvalid;
Ya que la prop state ya no existe y ahora es isInvalid, esta variable sería más bien `transfromedIsInvalid`

2023-04-18 16:58 UTC, Andresbl123 commented on src/components/inputs/Label/index.jsx
> +    typeof isInvalid === "boolean" ? isInvalid : defaultIsInvalid;
Resuelto

2023-04-18 16:58 UTC, Andresbl123 commented on src/components/inputs/Label/styles.js
> +const getColorByState = (isDisabled, isFocused, isInvalid) => {
Resuelto

2023-04-18 21:54 UTC, wfercanas approved these changes

2023-04-18 21:54 UTC, merged